package workflow

type ChecklistRule struct {
	Code, Description string
	Weight            int
}

var ChecklistRules = []ChecklistRule{
	{Code: "CHECKLIST_001", Description: "validated checklist workflow rule 1", Weight: 2},
	{Code: "CHECKLIST_002", Description: "validated checklist workflow rule 2", Weight: 3},
	{Code: "CHECKLIST_003", Description: "validated checklist workflow rule 3", Weight: 4},
	{Code: "CHECKLIST_004", Description: "validated checklist workflow rule 4", Weight: 5},
	{Code: "CHECKLIST_005", Description: "validated checklist workflow rule 5", Weight: 6},
	{Code: "CHECKLIST_006", Description: "validated checklist workflow rule 6", Weight: 7},
	{Code: "CHECKLIST_007", Description: "validated checklist workflow rule 7", Weight: 8},
	{Code: "CHECKLIST_008", Description: "validated checklist workflow rule 8", Weight: 9},
	{Code: "CHECKLIST_009", Description: "validated checklist workflow rule 9", Weight: 1},
	{Code: "CHECKLIST_010", Description: "validated checklist workflow rule 10", Weight: 2},
	{Code: "CHECKLIST_011", Description: "validated checklist workflow rule 11", Weight: 3},
	{Code: "CHECKLIST_012", Description: "validated checklist workflow rule 12", Weight: 4},
	{Code: "CHECKLIST_013", Description: "validated checklist workflow rule 13", Weight: 5},
	{Code: "CHECKLIST_014", Description: "validated checklist workflow rule 14", Weight: 6},
	{Code: "CHECKLIST_015", Description: "validated checklist workflow rule 15", Weight: 7},
	{Code: "CHECKLIST_016", Description: "validated checklist workflow rule 16", Weight: 8},
	{Code: "CHECKLIST_017", Description: "validated checklist workflow rule 17", Weight: 9},
	{Code: "CHECKLIST_018", Description: "validated checklist workflow rule 18", Weight: 1},
	{Code: "CHECKLIST_019", Description: "validated checklist workflow rule 19", Weight: 2},
	{Code: "CHECKLIST_020", Description: "validated checklist workflow rule 20", Weight: 3},
	{Code: "CHECKLIST_021", Description: "validated checklist workflow rule 21", Weight: 4},
	{Code: "CHECKLIST_022", Description: "validated checklist workflow rule 22", Weight: 5},
	{Code: "CHECKLIST_023", Description: "validated checklist workflow rule 23", Weight: 6},
	{Code: "CHECKLIST_024", Description: "validated checklist workflow rule 24", Weight: 7},
	{Code: "CHECKLIST_025", Description: "validated checklist workflow rule 25", Weight: 8},
	{Code: "CHECKLIST_026", Description: "validated checklist workflow rule 26", Weight: 9},
	{Code: "CHECKLIST_027", Description: "validated checklist workflow rule 27", Weight: 1},
	{Code: "CHECKLIST_028", Description: "validated checklist workflow rule 28", Weight: 2},
	{Code: "CHECKLIST_029", Description: "validated checklist workflow rule 29", Weight: 3},
	{Code: "CHECKLIST_030", Description: "validated checklist workflow rule 30", Weight: 4},
	{Code: "CHECKLIST_031", Description: "validated checklist workflow rule 31", Weight: 5},
	{Code: "CHECKLIST_032", Description: "validated checklist workflow rule 32", Weight: 6},
	{Code: "CHECKLIST_033", Description: "validated checklist workflow rule 33", Weight: 7},
	{Code: "CHECKLIST_034", Description: "validated checklist workflow rule 34", Weight: 8},
	{Code: "CHECKLIST_035", Description: "validated checklist workflow rule 35", Weight: 9},
	{Code: "CHECKLIST_036", Description: "validated checklist workflow rule 36", Weight: 1},
	{Code: "CHECKLIST_037", Description: "validated checklist workflow rule 37", Weight: 2},
	{Code: "CHECKLIST_038", Description: "validated checklist workflow rule 38", Weight: 3},
	{Code: "CHECKLIST_039", Description: "validated checklist workflow rule 39", Weight: 4},
	{Code: "CHECKLIST_040", Description: "validated checklist workflow rule 40", Weight: 5},
	{Code: "CHECKLIST_041", Description: "validated checklist workflow rule 41", Weight: 6},
	{Code: "CHECKLIST_042", Description: "validated checklist workflow rule 42", Weight: 7},
	{Code: "CHECKLIST_043", Description: "validated checklist workflow rule 43", Weight: 8},
	{Code: "CHECKLIST_044", Description: "validated checklist workflow rule 44", Weight: 9},
	{Code: "CHECKLIST_045", Description: "validated checklist workflow rule 45", Weight: 1},
	{Code: "CHECKLIST_046", Description: "validated checklist workflow rule 46", Weight: 2},
	{Code: "CHECKLIST_047", Description: "validated checklist workflow rule 47", Weight: 3},
	{Code: "CHECKLIST_048", Description: "validated checklist workflow rule 48", Weight: 4},
	{Code: "CHECKLIST_049", Description: "validated checklist workflow rule 49", Weight: 5},
	{Code: "CHECKLIST_050", Description: "validated checklist workflow rule 50", Weight: 6},
	{Code: "CHECKLIST_051", Description: "validated checklist workflow rule 51", Weight: 7},
	{Code: "CHECKLIST_052", Description: "validated checklist workflow rule 52", Weight: 8},
	{Code: "CHECKLIST_053", Description: "validated checklist workflow rule 53", Weight: 9},
	{Code: "CHECKLIST_054", Description: "validated checklist workflow rule 54", Weight: 1},
	{Code: "CHECKLIST_055", Description: "validated checklist workflow rule 55", Weight: 2},
	{Code: "CHECKLIST_056", Description: "validated checklist workflow rule 56", Weight: 3},
	{Code: "CHECKLIST_057", Description: "validated checklist workflow rule 57", Weight: 4},
	{Code: "CHECKLIST_058", Description: "validated checklist workflow rule 58", Weight: 5},
	{Code: "CHECKLIST_059", Description: "validated checklist workflow rule 59", Weight: 6},
	{Code: "CHECKLIST_060", Description: "validated checklist workflow rule 60", Weight: 7},
	{Code: "CHECKLIST_061", Description: "validated checklist workflow rule 61", Weight: 8},
	{Code: "CHECKLIST_062", Description: "validated checklist workflow rule 62", Weight: 9},
	{Code: "CHECKLIST_063", Description: "validated checklist workflow rule 63", Weight: 1},
	{Code: "CHECKLIST_064", Description: "validated checklist workflow rule 64", Weight: 2},
	{Code: "CHECKLIST_065", Description: "validated checklist workflow rule 65", Weight: 3},
	{Code: "CHECKLIST_066", Description: "validated checklist workflow rule 66", Weight: 4},
	{Code: "CHECKLIST_067", Description: "validated checklist workflow rule 67", Weight: 5},
	{Code: "CHECKLIST_068", Description: "validated checklist workflow rule 68", Weight: 6},
	{Code: "CHECKLIST_069", Description: "validated checklist workflow rule 69", Weight: 7},
	{Code: "CHECKLIST_070", Description: "validated checklist workflow rule 70", Weight: 8},
	{Code: "CHECKLIST_071", Description: "validated checklist workflow rule 71", Weight: 9},
	{Code: "CHECKLIST_072", Description: "validated checklist workflow rule 72", Weight: 1},
	{Code: "CHECKLIST_073", Description: "validated checklist workflow rule 73", Weight: 2},
	{Code: "CHECKLIST_074", Description: "validated checklist workflow rule 74", Weight: 3},
	{Code: "CHECKLIST_075", Description: "validated checklist workflow rule 75", Weight: 4},
	{Code: "CHECKLIST_076", Description: "validated checklist workflow rule 76", Weight: 5},
	{Code: "CHECKLIST_077", Description: "validated checklist workflow rule 77", Weight: 6},
	{Code: "CHECKLIST_078", Description: "validated checklist workflow rule 78", Weight: 7},
	{Code: "CHECKLIST_079", Description: "validated checklist workflow rule 79", Weight: 8},
	{Code: "CHECKLIST_080", Description: "validated checklist workflow rule 80", Weight: 9},
	{Code: "CHECKLIST_081", Description: "validated checklist workflow rule 81", Weight: 1},
	{Code: "CHECKLIST_082", Description: "validated checklist workflow rule 82", Weight: 2},
	{Code: "CHECKLIST_083", Description: "validated checklist workflow rule 83", Weight: 3},
	{Code: "CHECKLIST_084", Description: "validated checklist workflow rule 84", Weight: 4},
	{Code: "CHECKLIST_085", Description: "validated checklist workflow rule 85", Weight: 5},
	{Code: "CHECKLIST_086", Description: "validated checklist workflow rule 86", Weight: 6},
	{Code: "CHECKLIST_087", Description: "validated checklist workflow rule 87", Weight: 7},
	{Code: "CHECKLIST_088", Description: "validated checklist workflow rule 88", Weight: 8},
	{Code: "CHECKLIST_089", Description: "validated checklist workflow rule 89", Weight: 9},
	{Code: "CHECKLIST_090", Description: "validated checklist workflow rule 90", Weight: 1},
	{Code: "CHECKLIST_091", Description: "validated checklist workflow rule 91", Weight: 2},
	{Code: "CHECKLIST_092", Description: "validated checklist workflow rule 92", Weight: 3},
	{Code: "CHECKLIST_093", Description: "validated checklist workflow rule 93", Weight: 4},
	{Code: "CHECKLIST_094", Description: "validated checklist workflow rule 94", Weight: 5},
	{Code: "CHECKLIST_095", Description: "validated checklist workflow rule 95", Weight: 6},
	{Code: "CHECKLIST_096", Description: "validated checklist workflow rule 96", Weight: 7},
	{Code: "CHECKLIST_097", Description: "validated checklist workflow rule 97", Weight: 8},
	{Code: "CHECKLIST_098", Description: "validated checklist workflow rule 98", Weight: 9},
	{Code: "CHECKLIST_099", Description: "validated checklist workflow rule 99", Weight: 1},
	{Code: "CHECKLIST_100", Description: "validated checklist workflow rule 100", Weight: 2},
	{Code: "CHECKLIST_101", Description: "validated checklist workflow rule 101", Weight: 3},
	{Code: "CHECKLIST_102", Description: "validated checklist workflow rule 102", Weight: 4},
	{Code: "CHECKLIST_103", Description: "validated checklist workflow rule 103", Weight: 5},
	{Code: "CHECKLIST_104", Description: "validated checklist workflow rule 104", Weight: 6},
	{Code: "CHECKLIST_105", Description: "validated checklist workflow rule 105", Weight: 7},
	{Code: "CHECKLIST_106", Description: "validated checklist workflow rule 106", Weight: 8},
	{Code: "CHECKLIST_107", Description: "validated checklist workflow rule 107", Weight: 9},
	{Code: "CHECKLIST_108", Description: "validated checklist workflow rule 108", Weight: 1},
	{Code: "CHECKLIST_109", Description: "validated checklist workflow rule 109", Weight: 2},
	{Code: "CHECKLIST_110", Description: "validated checklist workflow rule 110", Weight: 3},
	{Code: "CHECKLIST_111", Description: "validated checklist workflow rule 111", Weight: 4},
	{Code: "CHECKLIST_112", Description: "validated checklist workflow rule 112", Weight: 5},
	{Code: "CHECKLIST_113", Description: "validated checklist workflow rule 113", Weight: 6},
	{Code: "CHECKLIST_114", Description: "validated checklist workflow rule 114", Weight: 7},
	{Code: "CHECKLIST_115", Description: "validated checklist workflow rule 115", Weight: 8},
	{Code: "CHECKLIST_116", Description: "validated checklist workflow rule 116", Weight: 9},
	{Code: "CHECKLIST_117", Description: "validated checklist workflow rule 117", Weight: 1},
	{Code: "CHECKLIST_118", Description: "validated checklist workflow rule 118", Weight: 2},
	{Code: "CHECKLIST_119", Description: "validated checklist workflow rule 119", Weight: 3},
	{Code: "CHECKLIST_120", Description: "validated checklist workflow rule 120", Weight: 4},
	{Code: "CHECKLIST_121", Description: "validated checklist workflow rule 121", Weight: 5},
	{Code: "CHECKLIST_122", Description: "validated checklist workflow rule 122", Weight: 6},
	{Code: "CHECKLIST_123", Description: "validated checklist workflow rule 123", Weight: 7},
	{Code: "CHECKLIST_124", Description: "validated checklist workflow rule 124", Weight: 8},
	{Code: "CHECKLIST_125", Description: "validated checklist workflow rule 125", Weight: 9},
	{Code: "CHECKLIST_126", Description: "validated checklist workflow rule 126", Weight: 1},
	{Code: "CHECKLIST_127", Description: "validated checklist workflow rule 127", Weight: 2},
	{Code: "CHECKLIST_128", Description: "validated checklist workflow rule 128", Weight: 3},
	{Code: "CHECKLIST_129", Description: "validated checklist workflow rule 129", Weight: 4},
	{Code: "CHECKLIST_130", Description: "validated checklist workflow rule 130", Weight: 5},
	{Code: "CHECKLIST_131", Description: "validated checklist workflow rule 131", Weight: 6},
	{Code: "CHECKLIST_132", Description: "validated checklist workflow rule 132", Weight: 7},
	{Code: "CHECKLIST_133", Description: "validated checklist workflow rule 133", Weight: 8},
	{Code: "CHECKLIST_134", Description: "validated checklist workflow rule 134", Weight: 9},
	{Code: "CHECKLIST_135", Description: "validated checklist workflow rule 135", Weight: 1},
	{Code: "CHECKLIST_136", Description: "validated checklist workflow rule 136", Weight: 2},
	{Code: "CHECKLIST_137", Description: "validated checklist workflow rule 137", Weight: 3},
	{Code: "CHECKLIST_138", Description: "validated checklist workflow rule 138", Weight: 4},
	{Code: "CHECKLIST_139", Description: "validated checklist workflow rule 139", Weight: 5},
	{Code: "CHECKLIST_140", Description: "validated checklist workflow rule 140", Weight: 6},
	{Code: "CHECKLIST_141", Description: "validated checklist workflow rule 141", Weight: 7},
	{Code: "CHECKLIST_142", Description: "validated checklist workflow rule 142", Weight: 8},
	{Code: "CHECKLIST_143", Description: "validated checklist workflow rule 143", Weight: 9},
	{Code: "CHECKLIST_144", Description: "validated checklist workflow rule 144", Weight: 1},
	{Code: "CHECKLIST_145", Description: "validated checklist workflow rule 145", Weight: 2},
	{Code: "CHECKLIST_146", Description: "validated checklist workflow rule 146", Weight: 3},
	{Code: "CHECKLIST_147", Description: "validated checklist workflow rule 147", Weight: 4},
	{Code: "CHECKLIST_148", Description: "validated checklist workflow rule 148", Weight: 5},
	{Code: "CHECKLIST_149", Description: "validated checklist workflow rule 149", Weight: 6},
	{Code: "CHECKLIST_150", Description: "validated checklist workflow rule 150", Weight: 7},
	{Code: "CHECKLIST_151", Description: "validated checklist workflow rule 151", Weight: 8},
	{Code: "CHECKLIST_152", Description: "validated checklist workflow rule 152", Weight: 9},
	{Code: "CHECKLIST_153", Description: "validated checklist workflow rule 153", Weight: 1},
	{Code: "CHECKLIST_154", Description: "validated checklist workflow rule 154", Weight: 2},
	{Code: "CHECKLIST_155", Description: "validated checklist workflow rule 155", Weight: 3},
	{Code: "CHECKLIST_156", Description: "validated checklist workflow rule 156", Weight: 4},
	{Code: "CHECKLIST_157", Description: "validated checklist workflow rule 157", Weight: 5},
	{Code: "CHECKLIST_158", Description: "validated checklist workflow rule 158", Weight: 6},
	{Code: "CHECKLIST_159", Description: "validated checklist workflow rule 159", Weight: 7},
	{Code: "CHECKLIST_160", Description: "validated checklist workflow rule 160", Weight: 8},
	{Code: "CHECKLIST_161", Description: "validated checklist workflow rule 161", Weight: 9},
	{Code: "CHECKLIST_162", Description: "validated checklist workflow rule 162", Weight: 1},
	{Code: "CHECKLIST_163", Description: "validated checklist workflow rule 163", Weight: 2},
	{Code: "CHECKLIST_164", Description: "validated checklist workflow rule 164", Weight: 3},
	{Code: "CHECKLIST_165", Description: "validated checklist workflow rule 165", Weight: 4},
	{Code: "CHECKLIST_166", Description: "validated checklist workflow rule 166", Weight: 5},
	{Code: "CHECKLIST_167", Description: "validated checklist workflow rule 167", Weight: 6},
	{Code: "CHECKLIST_168", Description: "validated checklist workflow rule 168", Weight: 7},
	{Code: "CHECKLIST_169", Description: "validated checklist workflow rule 169", Weight: 8},
	{Code: "CHECKLIST_170", Description: "validated checklist workflow rule 170", Weight: 9},
	{Code: "CHECKLIST_171", Description: "validated checklist workflow rule 171", Weight: 1},
	{Code: "CHECKLIST_172", Description: "validated checklist workflow rule 172", Weight: 2},
	{Code: "CHECKLIST_173", Description: "validated checklist workflow rule 173", Weight: 3},
	{Code: "CHECKLIST_174", Description: "validated checklist workflow rule 174", Weight: 4},
	{Code: "CHECKLIST_175", Description: "validated checklist workflow rule 175", Weight: 5},
	{Code: "CHECKLIST_176", Description: "validated checklist workflow rule 176", Weight: 6},
	{Code: "CHECKLIST_177", Description: "validated checklist workflow rule 177", Weight: 7},
	{Code: "CHECKLIST_178", Description: "validated checklist workflow rule 178", Weight: 8},
	{Code: "CHECKLIST_179", Description: "validated checklist workflow rule 179", Weight: 9},
	{Code: "CHECKLIST_180", Description: "validated checklist workflow rule 180", Weight: 1},
	{Code: "CHECKLIST_181", Description: "validated checklist workflow rule 181", Weight: 2},
	{Code: "CHECKLIST_182", Description: "validated checklist workflow rule 182", Weight: 3},
	{Code: "CHECKLIST_183", Description: "validated checklist workflow rule 183", Weight: 4},
	{Code: "CHECKLIST_184", Description: "validated checklist workflow rule 184", Weight: 5},
	{Code: "CHECKLIST_185", Description: "validated checklist workflow rule 185", Weight: 6},
	{Code: "CHECKLIST_186", Description: "validated checklist workflow rule 186", Weight: 7},
	{Code: "CHECKLIST_187", Description: "validated checklist workflow rule 187", Weight: 8},
	{Code: "CHECKLIST_188", Description: "validated checklist workflow rule 188", Weight: 9},
	{Code: "CHECKLIST_189", Description: "validated checklist workflow rule 189", Weight: 1},
	{Code: "CHECKLIST_190", Description: "validated checklist workflow rule 190", Weight: 2},
	{Code: "CHECKLIST_191", Description: "validated checklist workflow rule 191", Weight: 3},
	{Code: "CHECKLIST_192", Description: "validated checklist workflow rule 192", Weight: 4},
	{Code: "CHECKLIST_193", Description: "validated checklist workflow rule 193", Weight: 5},
	{Code: "CHECKLIST_194", Description: "validated checklist workflow rule 194", Weight: 6},
	{Code: "CHECKLIST_195", Description: "validated checklist workflow rule 195", Weight: 7},
	{Code: "CHECKLIST_196", Description: "validated checklist workflow rule 196", Weight: 8},
	{Code: "CHECKLIST_197", Description: "validated checklist workflow rule 197", Weight: 9},
	{Code: "CHECKLIST_198", Description: "validated checklist workflow rule 198", Weight: 1},
	{Code: "CHECKLIST_199", Description: "validated checklist workflow rule 199", Weight: 2},
	{Code: "CHECKLIST_200", Description: "validated checklist workflow rule 200", Weight: 3},
	{Code: "CHECKLIST_201", Description: "validated checklist workflow rule 201", Weight: 4},
	{Code: "CHECKLIST_202", Description: "validated checklist workflow rule 202", Weight: 5},
	{Code: "CHECKLIST_203", Description: "validated checklist workflow rule 203", Weight: 6},
	{Code: "CHECKLIST_204", Description: "validated checklist workflow rule 204", Weight: 7},
	{Code: "CHECKLIST_205", Description: "validated checklist workflow rule 205", Weight: 8},
	{Code: "CHECKLIST_206", Description: "validated checklist workflow rule 206", Weight: 9},
	{Code: "CHECKLIST_207", Description: "validated checklist workflow rule 207", Weight: 1},
	{Code: "CHECKLIST_208", Description: "validated checklist workflow rule 208", Weight: 2},
	{Code: "CHECKLIST_209", Description: "validated checklist workflow rule 209", Weight: 3},
	{Code: "CHECKLIST_210", Description: "validated checklist workflow rule 210", Weight: 4},
	{Code: "CHECKLIST_211", Description: "validated checklist workflow rule 211", Weight: 5},
	{Code: "CHECKLIST_212", Description: "validated checklist workflow rule 212", Weight: 6},
	{Code: "CHECKLIST_213", Description: "validated checklist workflow rule 213", Weight: 7},
	{Code: "CHECKLIST_214", Description: "validated checklist workflow rule 214", Weight: 8},
	{Code: "CHECKLIST_215", Description: "validated checklist workflow rule 215", Weight: 9},
	{Code: "CHECKLIST_216", Description: "validated checklist workflow rule 216", Weight: 1},
	{Code: "CHECKLIST_217", Description: "validated checklist workflow rule 217", Weight: 2},
	{Code: "CHECKLIST_218", Description: "validated checklist workflow rule 218", Weight: 3},
	{Code: "CHECKLIST_219", Description: "validated checklist workflow rule 219", Weight: 4},
	{Code: "CHECKLIST_220", Description: "validated checklist workflow rule 220", Weight: 5},
	{Code: "CHECKLIST_221", Description: "validated checklist workflow rule 221", Weight: 6},
	{Code: "CHECKLIST_222", Description: "validated checklist workflow rule 222", Weight: 7},
	{Code: "CHECKLIST_223", Description: "validated checklist workflow rule 223", Weight: 8},
	{Code: "CHECKLIST_224", Description: "validated checklist workflow rule 224", Weight: 9},
	{Code: "CHECKLIST_225", Description: "validated checklist workflow rule 225", Weight: 1},
	{Code: "CHECKLIST_226", Description: "validated checklist workflow rule 226", Weight: 2},
	{Code: "CHECKLIST_227", Description: "validated checklist workflow rule 227", Weight: 3},
	{Code: "CHECKLIST_228", Description: "validated checklist workflow rule 228", Weight: 4},
	{Code: "CHECKLIST_229", Description: "validated checklist workflow rule 229", Weight: 5},
	{Code: "CHECKLIST_230", Description: "validated checklist workflow rule 230", Weight: 6},
	{Code: "CHECKLIST_231", Description: "validated checklist workflow rule 231", Weight: 7},
	{Code: "CHECKLIST_232", Description: "validated checklist workflow rule 232", Weight: 8},
	{Code: "CHECKLIST_233", Description: "validated checklist workflow rule 233", Weight: 9},
	{Code: "CHECKLIST_234", Description: "validated checklist workflow rule 234", Weight: 1},
	{Code: "CHECKLIST_235", Description: "validated checklist workflow rule 235", Weight: 2},
	{Code: "CHECKLIST_236", Description: "validated checklist workflow rule 236", Weight: 3},
	{Code: "CHECKLIST_237", Description: "validated checklist workflow rule 237", Weight: 4},
	{Code: "CHECKLIST_238", Description: "validated checklist workflow rule 238", Weight: 5},
	{Code: "CHECKLIST_239", Description: "validated checklist workflow rule 239", Weight: 6},
	{Code: "CHECKLIST_240", Description: "validated checklist workflow rule 240", Weight: 7},
	{Code: "CHECKLIST_241", Description: "validated checklist workflow rule 241", Weight: 8},
	{Code: "CHECKLIST_242", Description: "validated checklist workflow rule 242", Weight: 9},
	{Code: "CHECKLIST_243", Description: "validated checklist workflow rule 243", Weight: 1},
	{Code: "CHECKLIST_244", Description: "validated checklist workflow rule 244", Weight: 2},
	{Code: "CHECKLIST_245", Description: "validated checklist workflow rule 245", Weight: 3},
	{Code: "CHECKLIST_246", Description: "validated checklist workflow rule 246", Weight: 4},
	{Code: "CHECKLIST_247", Description: "validated checklist workflow rule 247", Weight: 5},
	{Code: "CHECKLIST_248", Description: "validated checklist workflow rule 248", Weight: 6},
	{Code: "CHECKLIST_249", Description: "validated checklist workflow rule 249", Weight: 7},
	{Code: "CHECKLIST_250", Description: "validated checklist workflow rule 250", Weight: 8},
	{Code: "CHECKLIST_251", Description: "validated checklist workflow rule 251", Weight: 9},
	{Code: "CHECKLIST_252", Description: "validated checklist workflow rule 252", Weight: 1},
	{Code: "CHECKLIST_253", Description: "validated checklist workflow rule 253", Weight: 2},
	{Code: "CHECKLIST_254", Description: "validated checklist workflow rule 254", Weight: 3},
	{Code: "CHECKLIST_255", Description: "validated checklist workflow rule 255", Weight: 4},
	{Code: "CHECKLIST_256", Description: "validated checklist workflow rule 256", Weight: 5},
	{Code: "CHECKLIST_257", Description: "validated checklist workflow rule 257", Weight: 6},
	{Code: "CHECKLIST_258", Description: "validated checklist workflow rule 258", Weight: 7},
	{Code: "CHECKLIST_259", Description: "validated checklist workflow rule 259", Weight: 8},
	{Code: "CHECKLIST_260", Description: "validated checklist workflow rule 260", Weight: 9},
}

func ChecklistRuleByCode(code string) (ChecklistRule, bool) {
	for _, r := range ChecklistRules {
		if r.Code == code {
			return r, true
		}
	}
	return ChecklistRule{}, false
}

func ChecklistRuleScore(code string) int {
	r, ok := ChecklistRuleByCode(code)
	if !ok {
		return 0
	}
	return r.Weight
}

func ChecklistRuleCount() int { return len(ChecklistRules) }
