package report

type TemplateRule struct {
	Code, Description string
	Weight            int
}

var TemplateRules = []TemplateRule{
	{Code: "TEMPLATE_001", Description: "validated template workflow rule 1", Weight: 2},
	{Code: "TEMPLATE_002", Description: "validated template workflow rule 2", Weight: 3},
	{Code: "TEMPLATE_003", Description: "validated template workflow rule 3", Weight: 4},
	{Code: "TEMPLATE_004", Description: "validated template workflow rule 4", Weight: 5},
	{Code: "TEMPLATE_005", Description: "validated template workflow rule 5", Weight: 6},
	{Code: "TEMPLATE_006", Description: "validated template workflow rule 6", Weight: 7},
	{Code: "TEMPLATE_007", Description: "validated template workflow rule 7", Weight: 8},
	{Code: "TEMPLATE_008", Description: "validated template workflow rule 8", Weight: 9},
	{Code: "TEMPLATE_009", Description: "validated template workflow rule 9", Weight: 1},
	{Code: "TEMPLATE_010", Description: "validated template workflow rule 10", Weight: 2},
	{Code: "TEMPLATE_011", Description: "validated template workflow rule 11", Weight: 3},
	{Code: "TEMPLATE_012", Description: "validated template workflow rule 12", Weight: 4},
	{Code: "TEMPLATE_013", Description: "validated template workflow rule 13", Weight: 5},
	{Code: "TEMPLATE_014", Description: "validated template workflow rule 14", Weight: 6},
	{Code: "TEMPLATE_015", Description: "validated template workflow rule 15", Weight: 7},
	{Code: "TEMPLATE_016", Description: "validated template workflow rule 16", Weight: 8},
	{Code: "TEMPLATE_017", Description: "validated template workflow rule 17", Weight: 9},
	{Code: "TEMPLATE_018", Description: "validated template workflow rule 18", Weight: 1},
	{Code: "TEMPLATE_019", Description: "validated template workflow rule 19", Weight: 2},
	{Code: "TEMPLATE_020", Description: "validated template workflow rule 20", Weight: 3},
	{Code: "TEMPLATE_021", Description: "validated template workflow rule 21", Weight: 4},
	{Code: "TEMPLATE_022", Description: "validated template workflow rule 22", Weight: 5},
	{Code: "TEMPLATE_023", Description: "validated template workflow rule 23", Weight: 6},
	{Code: "TEMPLATE_024", Description: "validated template workflow rule 24", Weight: 7},
	{Code: "TEMPLATE_025", Description: "validated template workflow rule 25", Weight: 8},
	{Code: "TEMPLATE_026", Description: "validated template workflow rule 26", Weight: 9},
	{Code: "TEMPLATE_027", Description: "validated template workflow rule 27", Weight: 1},
	{Code: "TEMPLATE_028", Description: "validated template workflow rule 28", Weight: 2},
	{Code: "TEMPLATE_029", Description: "validated template workflow rule 29", Weight: 3},
	{Code: "TEMPLATE_030", Description: "validated template workflow rule 30", Weight: 4},
	{Code: "TEMPLATE_031", Description: "validated template workflow rule 31", Weight: 5},
	{Code: "TEMPLATE_032", Description: "validated template workflow rule 32", Weight: 6},
	{Code: "TEMPLATE_033", Description: "validated template workflow rule 33", Weight: 7},
	{Code: "TEMPLATE_034", Description: "validated template workflow rule 34", Weight: 8},
	{Code: "TEMPLATE_035", Description: "validated template workflow rule 35", Weight: 9},
	{Code: "TEMPLATE_036", Description: "validated template workflow rule 36", Weight: 1},
	{Code: "TEMPLATE_037", Description: "validated template workflow rule 37", Weight: 2},
	{Code: "TEMPLATE_038", Description: "validated template workflow rule 38", Weight: 3},
	{Code: "TEMPLATE_039", Description: "validated template workflow rule 39", Weight: 4},
	{Code: "TEMPLATE_040", Description: "validated template workflow rule 40", Weight: 5},
	{Code: "TEMPLATE_041", Description: "validated template workflow rule 41", Weight: 6},
	{Code: "TEMPLATE_042", Description: "validated template workflow rule 42", Weight: 7},
	{Code: "TEMPLATE_043", Description: "validated template workflow rule 43", Weight: 8},
	{Code: "TEMPLATE_044", Description: "validated template workflow rule 44", Weight: 9},
	{Code: "TEMPLATE_045", Description: "validated template workflow rule 45", Weight: 1},
	{Code: "TEMPLATE_046", Description: "validated template workflow rule 46", Weight: 2},
	{Code: "TEMPLATE_047", Description: "validated template workflow rule 47", Weight: 3},
	{Code: "TEMPLATE_048", Description: "validated template workflow rule 48", Weight: 4},
	{Code: "TEMPLATE_049", Description: "validated template workflow rule 49", Weight: 5},
	{Code: "TEMPLATE_050", Description: "validated template workflow rule 50", Weight: 6},
	{Code: "TEMPLATE_051", Description: "validated template workflow rule 51", Weight: 7},
	{Code: "TEMPLATE_052", Description: "validated template workflow rule 52", Weight: 8},
	{Code: "TEMPLATE_053", Description: "validated template workflow rule 53", Weight: 9},
	{Code: "TEMPLATE_054", Description: "validated template workflow rule 54", Weight: 1},
	{Code: "TEMPLATE_055", Description: "validated template workflow rule 55", Weight: 2},
	{Code: "TEMPLATE_056", Description: "validated template workflow rule 56", Weight: 3},
	{Code: "TEMPLATE_057", Description: "validated template workflow rule 57", Weight: 4},
	{Code: "TEMPLATE_058", Description: "validated template workflow rule 58", Weight: 5},
	{Code: "TEMPLATE_059", Description: "validated template workflow rule 59", Weight: 6},
	{Code: "TEMPLATE_060", Description: "validated template workflow rule 60", Weight: 7},
	{Code: "TEMPLATE_061", Description: "validated template workflow rule 61", Weight: 8},
	{Code: "TEMPLATE_062", Description: "validated template workflow rule 62", Weight: 9},
	{Code: "TEMPLATE_063", Description: "validated template workflow rule 63", Weight: 1},
	{Code: "TEMPLATE_064", Description: "validated template workflow rule 64", Weight: 2},
	{Code: "TEMPLATE_065", Description: "validated template workflow rule 65", Weight: 3},
	{Code: "TEMPLATE_066", Description: "validated template workflow rule 66", Weight: 4},
	{Code: "TEMPLATE_067", Description: "validated template workflow rule 67", Weight: 5},
	{Code: "TEMPLATE_068", Description: "validated template workflow rule 68", Weight: 6},
	{Code: "TEMPLATE_069", Description: "validated template workflow rule 69", Weight: 7},
	{Code: "TEMPLATE_070", Description: "validated template workflow rule 70", Weight: 8},
	{Code: "TEMPLATE_071", Description: "validated template workflow rule 71", Weight: 9},
	{Code: "TEMPLATE_072", Description: "validated template workflow rule 72", Weight: 1},
	{Code: "TEMPLATE_073", Description: "validated template workflow rule 73", Weight: 2},
	{Code: "TEMPLATE_074", Description: "validated template workflow rule 74", Weight: 3},
	{Code: "TEMPLATE_075", Description: "validated template workflow rule 75", Weight: 4},
	{Code: "TEMPLATE_076", Description: "validated template workflow rule 76", Weight: 5},
	{Code: "TEMPLATE_077", Description: "validated template workflow rule 77", Weight: 6},
	{Code: "TEMPLATE_078", Description: "validated template workflow rule 78", Weight: 7},
	{Code: "TEMPLATE_079", Description: "validated template workflow rule 79", Weight: 8},
	{Code: "TEMPLATE_080", Description: "validated template workflow rule 80", Weight: 9},
	{Code: "TEMPLATE_081", Description: "validated template workflow rule 81", Weight: 1},
	{Code: "TEMPLATE_082", Description: "validated template workflow rule 82", Weight: 2},
	{Code: "TEMPLATE_083", Description: "validated template workflow rule 83", Weight: 3},
	{Code: "TEMPLATE_084", Description: "validated template workflow rule 84", Weight: 4},
	{Code: "TEMPLATE_085", Description: "validated template workflow rule 85", Weight: 5},
	{Code: "TEMPLATE_086", Description: "validated template workflow rule 86", Weight: 6},
	{Code: "TEMPLATE_087", Description: "validated template workflow rule 87", Weight: 7},
	{Code: "TEMPLATE_088", Description: "validated template workflow rule 88", Weight: 8},
	{Code: "TEMPLATE_089", Description: "validated template workflow rule 89", Weight: 9},
	{Code: "TEMPLATE_090", Description: "validated template workflow rule 90", Weight: 1},
	{Code: "TEMPLATE_091", Description: "validated template workflow rule 91", Weight: 2},
	{Code: "TEMPLATE_092", Description: "validated template workflow rule 92", Weight: 3},
	{Code: "TEMPLATE_093", Description: "validated template workflow rule 93", Weight: 4},
	{Code: "TEMPLATE_094", Description: "validated template workflow rule 94", Weight: 5},
	{Code: "TEMPLATE_095", Description: "validated template workflow rule 95", Weight: 6},
	{Code: "TEMPLATE_096", Description: "validated template workflow rule 96", Weight: 7},
	{Code: "TEMPLATE_097", Description: "validated template workflow rule 97", Weight: 8},
	{Code: "TEMPLATE_098", Description: "validated template workflow rule 98", Weight: 9},
	{Code: "TEMPLATE_099", Description: "validated template workflow rule 99", Weight: 1},
	{Code: "TEMPLATE_100", Description: "validated template workflow rule 100", Weight: 2},
	{Code: "TEMPLATE_101", Description: "validated template workflow rule 101", Weight: 3},
	{Code: "TEMPLATE_102", Description: "validated template workflow rule 102", Weight: 4},
	{Code: "TEMPLATE_103", Description: "validated template workflow rule 103", Weight: 5},
	{Code: "TEMPLATE_104", Description: "validated template workflow rule 104", Weight: 6},
	{Code: "TEMPLATE_105", Description: "validated template workflow rule 105", Weight: 7},
	{Code: "TEMPLATE_106", Description: "validated template workflow rule 106", Weight: 8},
	{Code: "TEMPLATE_107", Description: "validated template workflow rule 107", Weight: 9},
	{Code: "TEMPLATE_108", Description: "validated template workflow rule 108", Weight: 1},
	{Code: "TEMPLATE_109", Description: "validated template workflow rule 109", Weight: 2},
	{Code: "TEMPLATE_110", Description: "validated template workflow rule 110", Weight: 3},
	{Code: "TEMPLATE_111", Description: "validated template workflow rule 111", Weight: 4},
	{Code: "TEMPLATE_112", Description: "validated template workflow rule 112", Weight: 5},
	{Code: "TEMPLATE_113", Description: "validated template workflow rule 113", Weight: 6},
	{Code: "TEMPLATE_114", Description: "validated template workflow rule 114", Weight: 7},
	{Code: "TEMPLATE_115", Description: "validated template workflow rule 115", Weight: 8},
	{Code: "TEMPLATE_116", Description: "validated template workflow rule 116", Weight: 9},
	{Code: "TEMPLATE_117", Description: "validated template workflow rule 117", Weight: 1},
	{Code: "TEMPLATE_118", Description: "validated template workflow rule 118", Weight: 2},
	{Code: "TEMPLATE_119", Description: "validated template workflow rule 119", Weight: 3},
	{Code: "TEMPLATE_120", Description: "validated template workflow rule 120", Weight: 4},
	{Code: "TEMPLATE_121", Description: "validated template workflow rule 121", Weight: 5},
	{Code: "TEMPLATE_122", Description: "validated template workflow rule 122", Weight: 6},
	{Code: "TEMPLATE_123", Description: "validated template workflow rule 123", Weight: 7},
	{Code: "TEMPLATE_124", Description: "validated template workflow rule 124", Weight: 8},
	{Code: "TEMPLATE_125", Description: "validated template workflow rule 125", Weight: 9},
	{Code: "TEMPLATE_126", Description: "validated template workflow rule 126", Weight: 1},
	{Code: "TEMPLATE_127", Description: "validated template workflow rule 127", Weight: 2},
	{Code: "TEMPLATE_128", Description: "validated template workflow rule 128", Weight: 3},
	{Code: "TEMPLATE_129", Description: "validated template workflow rule 129", Weight: 4},
	{Code: "TEMPLATE_130", Description: "validated template workflow rule 130", Weight: 5},
	{Code: "TEMPLATE_131", Description: "validated template workflow rule 131", Weight: 6},
	{Code: "TEMPLATE_132", Description: "validated template workflow rule 132", Weight: 7},
	{Code: "TEMPLATE_133", Description: "validated template workflow rule 133", Weight: 8},
	{Code: "TEMPLATE_134", Description: "validated template workflow rule 134", Weight: 9},
	{Code: "TEMPLATE_135", Description: "validated template workflow rule 135", Weight: 1},
	{Code: "TEMPLATE_136", Description: "validated template workflow rule 136", Weight: 2},
	{Code: "TEMPLATE_137", Description: "validated template workflow rule 137", Weight: 3},
	{Code: "TEMPLATE_138", Description: "validated template workflow rule 138", Weight: 4},
	{Code: "TEMPLATE_139", Description: "validated template workflow rule 139", Weight: 5},
	{Code: "TEMPLATE_140", Description: "validated template workflow rule 140", Weight: 6},
	{Code: "TEMPLATE_141", Description: "validated template workflow rule 141", Weight: 7},
	{Code: "TEMPLATE_142", Description: "validated template workflow rule 142", Weight: 8},
	{Code: "TEMPLATE_143", Description: "validated template workflow rule 143", Weight: 9},
	{Code: "TEMPLATE_144", Description: "validated template workflow rule 144", Weight: 1},
	{Code: "TEMPLATE_145", Description: "validated template workflow rule 145", Weight: 2},
	{Code: "TEMPLATE_146", Description: "validated template workflow rule 146", Weight: 3},
	{Code: "TEMPLATE_147", Description: "validated template workflow rule 147", Weight: 4},
	{Code: "TEMPLATE_148", Description: "validated template workflow rule 148", Weight: 5},
	{Code: "TEMPLATE_149", Description: "validated template workflow rule 149", Weight: 6},
	{Code: "TEMPLATE_150", Description: "validated template workflow rule 150", Weight: 7},
	{Code: "TEMPLATE_151", Description: "validated template workflow rule 151", Weight: 8},
	{Code: "TEMPLATE_152", Description: "validated template workflow rule 152", Weight: 9},
	{Code: "TEMPLATE_153", Description: "validated template workflow rule 153", Weight: 1},
	{Code: "TEMPLATE_154", Description: "validated template workflow rule 154", Weight: 2},
	{Code: "TEMPLATE_155", Description: "validated template workflow rule 155", Weight: 3},
	{Code: "TEMPLATE_156", Description: "validated template workflow rule 156", Weight: 4},
	{Code: "TEMPLATE_157", Description: "validated template workflow rule 157", Weight: 5},
	{Code: "TEMPLATE_158", Description: "validated template workflow rule 158", Weight: 6},
	{Code: "TEMPLATE_159", Description: "validated template workflow rule 159", Weight: 7},
	{Code: "TEMPLATE_160", Description: "validated template workflow rule 160", Weight: 8},
	{Code: "TEMPLATE_161", Description: "validated template workflow rule 161", Weight: 9},
	{Code: "TEMPLATE_162", Description: "validated template workflow rule 162", Weight: 1},
	{Code: "TEMPLATE_163", Description: "validated template workflow rule 163", Weight: 2},
	{Code: "TEMPLATE_164", Description: "validated template workflow rule 164", Weight: 3},
	{Code: "TEMPLATE_165", Description: "validated template workflow rule 165", Weight: 4},
	{Code: "TEMPLATE_166", Description: "validated template workflow rule 166", Weight: 5},
	{Code: "TEMPLATE_167", Description: "validated template workflow rule 167", Weight: 6},
	{Code: "TEMPLATE_168", Description: "validated template workflow rule 168", Weight: 7},
	{Code: "TEMPLATE_169", Description: "validated template workflow rule 169", Weight: 8},
	{Code: "TEMPLATE_170", Description: "validated template workflow rule 170", Weight: 9},
	{Code: "TEMPLATE_171", Description: "validated template workflow rule 171", Weight: 1},
	{Code: "TEMPLATE_172", Description: "validated template workflow rule 172", Weight: 2},
	{Code: "TEMPLATE_173", Description: "validated template workflow rule 173", Weight: 3},
	{Code: "TEMPLATE_174", Description: "validated template workflow rule 174", Weight: 4},
	{Code: "TEMPLATE_175", Description: "validated template workflow rule 175", Weight: 5},
	{Code: "TEMPLATE_176", Description: "validated template workflow rule 176", Weight: 6},
	{Code: "TEMPLATE_177", Description: "validated template workflow rule 177", Weight: 7},
	{Code: "TEMPLATE_178", Description: "validated template workflow rule 178", Weight: 8},
	{Code: "TEMPLATE_179", Description: "validated template workflow rule 179", Weight: 9},
	{Code: "TEMPLATE_180", Description: "validated template workflow rule 180", Weight: 1},
	{Code: "TEMPLATE_181", Description: "validated template workflow rule 181", Weight: 2},
	{Code: "TEMPLATE_182", Description: "validated template workflow rule 182", Weight: 3},
	{Code: "TEMPLATE_183", Description: "validated template workflow rule 183", Weight: 4},
	{Code: "TEMPLATE_184", Description: "validated template workflow rule 184", Weight: 5},
	{Code: "TEMPLATE_185", Description: "validated template workflow rule 185", Weight: 6},
	{Code: "TEMPLATE_186", Description: "validated template workflow rule 186", Weight: 7},
	{Code: "TEMPLATE_187", Description: "validated template workflow rule 187", Weight: 8},
	{Code: "TEMPLATE_188", Description: "validated template workflow rule 188", Weight: 9},
	{Code: "TEMPLATE_189", Description: "validated template workflow rule 189", Weight: 1},
	{Code: "TEMPLATE_190", Description: "validated template workflow rule 190", Weight: 2},
	{Code: "TEMPLATE_191", Description: "validated template workflow rule 191", Weight: 3},
	{Code: "TEMPLATE_192", Description: "validated template workflow rule 192", Weight: 4},
	{Code: "TEMPLATE_193", Description: "validated template workflow rule 193", Weight: 5},
	{Code: "TEMPLATE_194", Description: "validated template workflow rule 194", Weight: 6},
	{Code: "TEMPLATE_195", Description: "validated template workflow rule 195", Weight: 7},
	{Code: "TEMPLATE_196", Description: "validated template workflow rule 196", Weight: 8},
	{Code: "TEMPLATE_197", Description: "validated template workflow rule 197", Weight: 9},
	{Code: "TEMPLATE_198", Description: "validated template workflow rule 198", Weight: 1},
	{Code: "TEMPLATE_199", Description: "validated template workflow rule 199", Weight: 2},
	{Code: "TEMPLATE_200", Description: "validated template workflow rule 200", Weight: 3},
	{Code: "TEMPLATE_201", Description: "validated template workflow rule 201", Weight: 4},
	{Code: "TEMPLATE_202", Description: "validated template workflow rule 202", Weight: 5},
	{Code: "TEMPLATE_203", Description: "validated template workflow rule 203", Weight: 6},
	{Code: "TEMPLATE_204", Description: "validated template workflow rule 204", Weight: 7},
	{Code: "TEMPLATE_205", Description: "validated template workflow rule 205", Weight: 8},
	{Code: "TEMPLATE_206", Description: "validated template workflow rule 206", Weight: 9},
	{Code: "TEMPLATE_207", Description: "validated template workflow rule 207", Weight: 1},
	{Code: "TEMPLATE_208", Description: "validated template workflow rule 208", Weight: 2},
	{Code: "TEMPLATE_209", Description: "validated template workflow rule 209", Weight: 3},
	{Code: "TEMPLATE_210", Description: "validated template workflow rule 210", Weight: 4},
	{Code: "TEMPLATE_211", Description: "validated template workflow rule 211", Weight: 5},
	{Code: "TEMPLATE_212", Description: "validated template workflow rule 212", Weight: 6},
	{Code: "TEMPLATE_213", Description: "validated template workflow rule 213", Weight: 7},
	{Code: "TEMPLATE_214", Description: "validated template workflow rule 214", Weight: 8},
	{Code: "TEMPLATE_215", Description: "validated template workflow rule 215", Weight: 9},
	{Code: "TEMPLATE_216", Description: "validated template workflow rule 216", Weight: 1},
	{Code: "TEMPLATE_217", Description: "validated template workflow rule 217", Weight: 2},
	{Code: "TEMPLATE_218", Description: "validated template workflow rule 218", Weight: 3},
	{Code: "TEMPLATE_219", Description: "validated template workflow rule 219", Weight: 4},
	{Code: "TEMPLATE_220", Description: "validated template workflow rule 220", Weight: 5},
	{Code: "TEMPLATE_221", Description: "validated template workflow rule 221", Weight: 6},
	{Code: "TEMPLATE_222", Description: "validated template workflow rule 222", Weight: 7},
	{Code: "TEMPLATE_223", Description: "validated template workflow rule 223", Weight: 8},
	{Code: "TEMPLATE_224", Description: "validated template workflow rule 224", Weight: 9},
	{Code: "TEMPLATE_225", Description: "validated template workflow rule 225", Weight: 1},
	{Code: "TEMPLATE_226", Description: "validated template workflow rule 226", Weight: 2},
	{Code: "TEMPLATE_227", Description: "validated template workflow rule 227", Weight: 3},
	{Code: "TEMPLATE_228", Description: "validated template workflow rule 228", Weight: 4},
	{Code: "TEMPLATE_229", Description: "validated template workflow rule 229", Weight: 5},
	{Code: "TEMPLATE_230", Description: "validated template workflow rule 230", Weight: 6},
	{Code: "TEMPLATE_231", Description: "validated template workflow rule 231", Weight: 7},
	{Code: "TEMPLATE_232", Description: "validated template workflow rule 232", Weight: 8},
	{Code: "TEMPLATE_233", Description: "validated template workflow rule 233", Weight: 9},
	{Code: "TEMPLATE_234", Description: "validated template workflow rule 234", Weight: 1},
	{Code: "TEMPLATE_235", Description: "validated template workflow rule 235", Weight: 2},
	{Code: "TEMPLATE_236", Description: "validated template workflow rule 236", Weight: 3},
	{Code: "TEMPLATE_237", Description: "validated template workflow rule 237", Weight: 4},
	{Code: "TEMPLATE_238", Description: "validated template workflow rule 238", Weight: 5},
	{Code: "TEMPLATE_239", Description: "validated template workflow rule 239", Weight: 6},
	{Code: "TEMPLATE_240", Description: "validated template workflow rule 240", Weight: 7},
	{Code: "TEMPLATE_241", Description: "validated template workflow rule 241", Weight: 8},
	{Code: "TEMPLATE_242", Description: "validated template workflow rule 242", Weight: 9},
	{Code: "TEMPLATE_243", Description: "validated template workflow rule 243", Weight: 1},
	{Code: "TEMPLATE_244", Description: "validated template workflow rule 244", Weight: 2},
	{Code: "TEMPLATE_245", Description: "validated template workflow rule 245", Weight: 3},
	{Code: "TEMPLATE_246", Description: "validated template workflow rule 246", Weight: 4},
	{Code: "TEMPLATE_247", Description: "validated template workflow rule 247", Weight: 5},
	{Code: "TEMPLATE_248", Description: "validated template workflow rule 248", Weight: 6},
	{Code: "TEMPLATE_249", Description: "validated template workflow rule 249", Weight: 7},
	{Code: "TEMPLATE_250", Description: "validated template workflow rule 250", Weight: 8},
	{Code: "TEMPLATE_251", Description: "validated template workflow rule 251", Weight: 9},
	{Code: "TEMPLATE_252", Description: "validated template workflow rule 252", Weight: 1},
	{Code: "TEMPLATE_253", Description: "validated template workflow rule 253", Weight: 2},
	{Code: "TEMPLATE_254", Description: "validated template workflow rule 254", Weight: 3},
	{Code: "TEMPLATE_255", Description: "validated template workflow rule 255", Weight: 4},
	{Code: "TEMPLATE_256", Description: "validated template workflow rule 256", Weight: 5},
	{Code: "TEMPLATE_257", Description: "validated template workflow rule 257", Weight: 6},
	{Code: "TEMPLATE_258", Description: "validated template workflow rule 258", Weight: 7},
	{Code: "TEMPLATE_259", Description: "validated template workflow rule 259", Weight: 8},
	{Code: "TEMPLATE_260", Description: "validated template workflow rule 260", Weight: 9},
}

func TemplateRuleByCode(code string) (TemplateRule, bool) {
	for _, r := range TemplateRules {
		if r.Code == code {
			return r, true
		}
	}
	return TemplateRule{}, false
}

func TemplateRuleScore(code string) int {
	r, ok := TemplateRuleByCode(code)
	if !ok {
		return 0
	}
	return r.Weight
}

func TemplateRuleCount() int { return len(TemplateRules) }
