package domain

type Indicator struct {
	Code, Name, Unit string
	Threshold        float64
}

var CropIndicators = []Indicator{
	{Code: "CROP_001", Name: "crop index 1", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_002", Name: "crop index 2", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_003", Name: "crop index 3", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_004", Name: "crop index 4", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_005", Name: "crop index 5", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_006", Name: "crop index 6", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_007", Name: "crop index 7", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_008", Name: "crop index 8", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_009", Name: "crop index 9", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_010", Name: "crop index 10", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_011", Name: "crop index 11", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_012", Name: "crop index 12", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_013", Name: "crop index 13", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_014", Name: "crop index 14", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_015", Name: "crop index 15", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_016", Name: "crop index 16", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_017", Name: "crop index 17", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_018", Name: "crop index 18", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_019", Name: "crop index 19", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_020", Name: "crop index 20", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_021", Name: "crop index 21", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_022", Name: "crop index 22", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_023", Name: "crop index 23", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_024", Name: "crop index 24", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_025", Name: "crop index 25", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_026", Name: "crop index 26", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_027", Name: "crop index 27", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_028", Name: "crop index 28", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_029", Name: "crop index 29", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_030", Name: "crop index 30", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_031", Name: "crop index 31", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_032", Name: "crop index 32", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_033", Name: "crop index 33", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_034", Name: "crop index 34", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_035", Name: "crop index 35", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_036", Name: "crop index 36", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_037", Name: "crop index 37", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_038", Name: "crop index 38", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_039", Name: "crop index 39", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_040", Name: "crop index 40", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_041", Name: "crop index 41", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_042", Name: "crop index 42", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_043", Name: "crop index 43", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_044", Name: "crop index 44", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_045", Name: "crop index 45", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_046", Name: "crop index 46", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_047", Name: "crop index 47", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_048", Name: "crop index 48", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_049", Name: "crop index 49", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_050", Name: "crop index 50", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_051", Name: "crop index 51", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_052", Name: "crop index 52", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_053", Name: "crop index 53", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_054", Name: "crop index 54", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_055", Name: "crop index 55", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_056", Name: "crop index 56", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_057", Name: "crop index 57", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_058", Name: "crop index 58", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_059", Name: "crop index 59", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_060", Name: "crop index 60", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_061", Name: "crop index 61", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_062", Name: "crop index 62", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_063", Name: "crop index 63", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_064", Name: "crop index 64", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_065", Name: "crop index 65", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_066", Name: "crop index 66", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_067", Name: "crop index 67", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_068", Name: "crop index 68", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_069", Name: "crop index 69", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_070", Name: "crop index 70", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_071", Name: "crop index 71", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_072", Name: "crop index 72", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_073", Name: "crop index 73", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_074", Name: "crop index 74", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_075", Name: "crop index 75", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_076", Name: "crop index 76", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_077", Name: "crop index 77", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_078", Name: "crop index 78", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_079", Name: "crop index 79", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_080", Name: "crop index 80", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_081", Name: "crop index 81", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_082", Name: "crop index 82", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_083", Name: "crop index 83", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_084", Name: "crop index 84", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_085", Name: "crop index 85", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_086", Name: "crop index 86", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_087", Name: "crop index 87", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_088", Name: "crop index 88", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_089", Name: "crop index 89", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_090", Name: "crop index 90", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_091", Name: "crop index 91", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_092", Name: "crop index 92", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_093", Name: "crop index 93", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_094", Name: "crop index 94", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_095", Name: "crop index 95", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_096", Name: "crop index 96", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_097", Name: "crop index 97", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_098", Name: "crop index 98", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_099", Name: "crop index 99", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_100", Name: "crop index 100", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_101", Name: "crop index 101", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_102", Name: "crop index 102", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_103", Name: "crop index 103", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_104", Name: "crop index 104", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_105", Name: "crop index 105", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_106", Name: "crop index 106", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_107", Name: "crop index 107", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_108", Name: "crop index 108", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_109", Name: "crop index 109", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_110", Name: "crop index 110", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_111", Name: "crop index 111", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_112", Name: "crop index 112", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_113", Name: "crop index 113", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_114", Name: "crop index 114", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_115", Name: "crop index 115", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_116", Name: "crop index 116", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_117", Name: "crop index 117", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_118", Name: "crop index 118", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_119", Name: "crop index 119", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_120", Name: "crop index 120", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_121", Name: "crop index 121", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_122", Name: "crop index 122", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_123", Name: "crop index 123", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_124", Name: "crop index 124", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_125", Name: "crop index 125", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_126", Name: "crop index 126", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_127", Name: "crop index 127", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_128", Name: "crop index 128", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_129", Name: "crop index 129", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_130", Name: "crop index 130", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_131", Name: "crop index 131", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_132", Name: "crop index 132", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_133", Name: "crop index 133", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_134", Name: "crop index 134", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_135", Name: "crop index 135", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_136", Name: "crop index 136", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_137", Name: "crop index 137", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_138", Name: "crop index 138", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_139", Name: "crop index 139", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_140", Name: "crop index 140", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_141", Name: "crop index 141", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_142", Name: "crop index 142", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_143", Name: "crop index 143", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_144", Name: "crop index 144", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_145", Name: "crop index 145", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_146", Name: "crop index 146", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_147", Name: "crop index 147", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_148", Name: "crop index 148", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_149", Name: "crop index 149", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_150", Name: "crop index 150", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_151", Name: "crop index 151", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_152", Name: "crop index 152", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_153", Name: "crop index 153", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_154", Name: "crop index 154", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_155", Name: "crop index 155", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_156", Name: "crop index 156", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_157", Name: "crop index 157", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_158", Name: "crop index 158", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_159", Name: "crop index 159", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_160", Name: "crop index 160", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_161", Name: "crop index 161", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_162", Name: "crop index 162", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_163", Name: "crop index 163", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_164", Name: "crop index 164", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_165", Name: "crop index 165", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_166", Name: "crop index 166", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_167", Name: "crop index 167", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_168", Name: "crop index 168", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_169", Name: "crop index 169", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_170", Name: "crop index 170", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_171", Name: "crop index 171", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_172", Name: "crop index 172", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_173", Name: "crop index 173", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_174", Name: "crop index 174", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_175", Name: "crop index 175", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_176", Name: "crop index 176", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_177", Name: "crop index 177", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_178", Name: "crop index 178", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_179", Name: "crop index 179", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_180", Name: "crop index 180", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_181", Name: "crop index 181", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_182", Name: "crop index 182", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_183", Name: "crop index 183", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_184", Name: "crop index 184", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_185", Name: "crop index 185", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_186", Name: "crop index 186", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_187", Name: "crop index 187", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_188", Name: "crop index 188", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_189", Name: "crop index 189", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_190", Name: "crop index 190", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_191", Name: "crop index 191", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_192", Name: "crop index 192", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_193", Name: "crop index 193", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_194", Name: "crop index 194", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_195", Name: "crop index 195", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_196", Name: "crop index 196", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_197", Name: "crop index 197", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_198", Name: "crop index 198", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_199", Name: "crop index 199", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_200", Name: "crop index 200", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_201", Name: "crop index 201", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_202", Name: "crop index 202", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_203", Name: "crop index 203", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_204", Name: "crop index 204", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_205", Name: "crop index 205", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_206", Name: "crop index 206", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_207", Name: "crop index 207", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_208", Name: "crop index 208", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_209", Name: "crop index 209", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_210", Name: "crop index 210", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_211", Name: "crop index 211", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_212", Name: "crop index 212", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_213", Name: "crop index 213", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_214", Name: "crop index 214", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_215", Name: "crop index 215", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_216", Name: "crop index 216", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_217", Name: "crop index 217", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_218", Name: "crop index 218", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_219", Name: "crop index 219", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_220", Name: "crop index 220", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_221", Name: "crop index 221", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_222", Name: "crop index 222", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_223", Name: "crop index 223", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_224", Name: "crop index 224", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_225", Name: "crop index 225", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_226", Name: "crop index 226", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_227", Name: "crop index 227", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_228", Name: "crop index 228", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_229", Name: "crop index 229", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_230", Name: "crop index 230", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_231", Name: "crop index 231", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_232", Name: "crop index 232", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_233", Name: "crop index 233", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_234", Name: "crop index 234", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_235", Name: "crop index 235", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_236", Name: "crop index 236", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_237", Name: "crop index 237", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_238", Name: "crop index 238", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_239", Name: "crop index 239", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_240", Name: "crop index 240", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_241", Name: "crop index 241", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_242", Name: "crop index 242", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_243", Name: "crop index 243", Unit: "ndvi", Threshold: 0.6},
	{Code: "CROP_244", Name: "crop index 244", Unit: "ndvi", Threshold: 0.7},
	{Code: "CROP_245", Name: "crop index 245", Unit: "ndvi", Threshold: 0.8},
	{Code: "CROP_246", Name: "crop index 246", Unit: "ndvi", Threshold: 0.9},
	{Code: "CROP_247", Name: "crop index 247", Unit: "ndvi", Threshold: 1},
	{Code: "CROP_248", Name: "crop index 248", Unit: "ndvi", Threshold: 1.1},
	{Code: "CROP_249", Name: "crop index 249", Unit: "ndvi", Threshold: 1.2},
	{Code: "CROP_250", Name: "crop index 250", Unit: "ndvi", Threshold: 1.3},
	{Code: "CROP_251", Name: "crop index 251", Unit: "ndvi", Threshold: 1.4},
	{Code: "CROP_252", Name: "crop index 252", Unit: "ndvi", Threshold: 1.5},
	{Code: "CROP_253", Name: "crop index 253", Unit: "ndvi", Threshold: 1.6},
	{Code: "CROP_254", Name: "crop index 254", Unit: "ndvi", Threshold: 1.7},
	{Code: "CROP_255", Name: "crop index 255", Unit: "ndvi", Threshold: 0.1},
	{Code: "CROP_256", Name: "crop index 256", Unit: "ndvi", Threshold: 0.2},
	{Code: "CROP_257", Name: "crop index 257", Unit: "ndvi", Threshold: 0.3},
	{Code: "CROP_258", Name: "crop index 258", Unit: "ndvi", Threshold: 0.4},
	{Code: "CROP_259", Name: "crop index 259", Unit: "ndvi", Threshold: 0.5},
	{Code: "CROP_260", Name: "crop index 260", Unit: "ndvi", Threshold: 0.6},
}

func IndicatorByCode(code string) (Indicator, bool) {
	for _, v := range CropIndicators {
		if v.Code == code {
			return v, true
		}
	}
	return Indicator{}, false
}

func IndicatorsAbove(value float64) []Indicator {
	out := []Indicator{}
	for _, v := range CropIndicators {
		if v.Threshold < value {
			out = append(out, v)
		}
	}
	return out
}

func IndicatorCount() int { return len(CropIndicators) }
