package api

type RouteRule struct {
	Code, Description string
	Weight            int
}

var RouteRules = []RouteRule{
	{Code: "ROUTE_001", Description: "validated route workflow rule 1", Weight: 2},
	{Code: "ROUTE_002", Description: "validated route workflow rule 2", Weight: 3},
	{Code: "ROUTE_003", Description: "validated route workflow rule 3", Weight: 4},
	{Code: "ROUTE_004", Description: "validated route workflow rule 4", Weight: 5},
	{Code: "ROUTE_005", Description: "validated route workflow rule 5", Weight: 6},
	{Code: "ROUTE_006", Description: "validated route workflow rule 6", Weight: 7},
	{Code: "ROUTE_007", Description: "validated route workflow rule 7", Weight: 8},
	{Code: "ROUTE_008", Description: "validated route workflow rule 8", Weight: 9},
	{Code: "ROUTE_009", Description: "validated route workflow rule 9", Weight: 1},
	{Code: "ROUTE_010", Description: "validated route workflow rule 10", Weight: 2},
	{Code: "ROUTE_011", Description: "validated route workflow rule 11", Weight: 3},
	{Code: "ROUTE_012", Description: "validated route workflow rule 12", Weight: 4},
	{Code: "ROUTE_013", Description: "validated route workflow rule 13", Weight: 5},
	{Code: "ROUTE_014", Description: "validated route workflow rule 14", Weight: 6},
	{Code: "ROUTE_015", Description: "validated route workflow rule 15", Weight: 7},
	{Code: "ROUTE_016", Description: "validated route workflow rule 16", Weight: 8},
	{Code: "ROUTE_017", Description: "validated route workflow rule 17", Weight: 9},
	{Code: "ROUTE_018", Description: "validated route workflow rule 18", Weight: 1},
	{Code: "ROUTE_019", Description: "validated route workflow rule 19", Weight: 2},
	{Code: "ROUTE_020", Description: "validated route workflow rule 20", Weight: 3},
	{Code: "ROUTE_021", Description: "validated route workflow rule 21", Weight: 4},
	{Code: "ROUTE_022", Description: "validated route workflow rule 22", Weight: 5},
	{Code: "ROUTE_023", Description: "validated route workflow rule 23", Weight: 6},
	{Code: "ROUTE_024", Description: "validated route workflow rule 24", Weight: 7},
	{Code: "ROUTE_025", Description: "validated route workflow rule 25", Weight: 8},
	{Code: "ROUTE_026", Description: "validated route workflow rule 26", Weight: 9},
	{Code: "ROUTE_027", Description: "validated route workflow rule 27", Weight: 1},
	{Code: "ROUTE_028", Description: "validated route workflow rule 28", Weight: 2},
	{Code: "ROUTE_029", Description: "validated route workflow rule 29", Weight: 3},
	{Code: "ROUTE_030", Description: "validated route workflow rule 30", Weight: 4},
	{Code: "ROUTE_031", Description: "validated route workflow rule 31", Weight: 5},
	{Code: "ROUTE_032", Description: "validated route workflow rule 32", Weight: 6},
	{Code: "ROUTE_033", Description: "validated route workflow rule 33", Weight: 7},
	{Code: "ROUTE_034", Description: "validated route workflow rule 34", Weight: 8},
	{Code: "ROUTE_035", Description: "validated route workflow rule 35", Weight: 9},
	{Code: "ROUTE_036", Description: "validated route workflow rule 36", Weight: 1},
	{Code: "ROUTE_037", Description: "validated route workflow rule 37", Weight: 2},
	{Code: "ROUTE_038", Description: "validated route workflow rule 38", Weight: 3},
	{Code: "ROUTE_039", Description: "validated route workflow rule 39", Weight: 4},
	{Code: "ROUTE_040", Description: "validated route workflow rule 40", Weight: 5},
	{Code: "ROUTE_041", Description: "validated route workflow rule 41", Weight: 6},
	{Code: "ROUTE_042", Description: "validated route workflow rule 42", Weight: 7},
	{Code: "ROUTE_043", Description: "validated route workflow rule 43", Weight: 8},
	{Code: "ROUTE_044", Description: "validated route workflow rule 44", Weight: 9},
	{Code: "ROUTE_045", Description: "validated route workflow rule 45", Weight: 1},
	{Code: "ROUTE_046", Description: "validated route workflow rule 46", Weight: 2},
	{Code: "ROUTE_047", Description: "validated route workflow rule 47", Weight: 3},
	{Code: "ROUTE_048", Description: "validated route workflow rule 48", Weight: 4},
	{Code: "ROUTE_049", Description: "validated route workflow rule 49", Weight: 5},
	{Code: "ROUTE_050", Description: "validated route workflow rule 50", Weight: 6},
	{Code: "ROUTE_051", Description: "validated route workflow rule 51", Weight: 7},
	{Code: "ROUTE_052", Description: "validated route workflow rule 52", Weight: 8},
	{Code: "ROUTE_053", Description: "validated route workflow rule 53", Weight: 9},
	{Code: "ROUTE_054", Description: "validated route workflow rule 54", Weight: 1},
	{Code: "ROUTE_055", Description: "validated route workflow rule 55", Weight: 2},
	{Code: "ROUTE_056", Description: "validated route workflow rule 56", Weight: 3},
	{Code: "ROUTE_057", Description: "validated route workflow rule 57", Weight: 4},
	{Code: "ROUTE_058", Description: "validated route workflow rule 58", Weight: 5},
	{Code: "ROUTE_059", Description: "validated route workflow rule 59", Weight: 6},
	{Code: "ROUTE_060", Description: "validated route workflow rule 60", Weight: 7},
	{Code: "ROUTE_061", Description: "validated route workflow rule 61", Weight: 8},
	{Code: "ROUTE_062", Description: "validated route workflow rule 62", Weight: 9},
	{Code: "ROUTE_063", Description: "validated route workflow rule 63", Weight: 1},
	{Code: "ROUTE_064", Description: "validated route workflow rule 64", Weight: 2},
	{Code: "ROUTE_065", Description: "validated route workflow rule 65", Weight: 3},
	{Code: "ROUTE_066", Description: "validated route workflow rule 66", Weight: 4},
	{Code: "ROUTE_067", Description: "validated route workflow rule 67", Weight: 5},
	{Code: "ROUTE_068", Description: "validated route workflow rule 68", Weight: 6},
	{Code: "ROUTE_069", Description: "validated route workflow rule 69", Weight: 7},
	{Code: "ROUTE_070", Description: "validated route workflow rule 70", Weight: 8},
	{Code: "ROUTE_071", Description: "validated route workflow rule 71", Weight: 9},
	{Code: "ROUTE_072", Description: "validated route workflow rule 72", Weight: 1},
	{Code: "ROUTE_073", Description: "validated route workflow rule 73", Weight: 2},
	{Code: "ROUTE_074", Description: "validated route workflow rule 74", Weight: 3},
	{Code: "ROUTE_075", Description: "validated route workflow rule 75", Weight: 4},
	{Code: "ROUTE_076", Description: "validated route workflow rule 76", Weight: 5},
	{Code: "ROUTE_077", Description: "validated route workflow rule 77", Weight: 6},
	{Code: "ROUTE_078", Description: "validated route workflow rule 78", Weight: 7},
	{Code: "ROUTE_079", Description: "validated route workflow rule 79", Weight: 8},
	{Code: "ROUTE_080", Description: "validated route workflow rule 80", Weight: 9},
	{Code: "ROUTE_081", Description: "validated route workflow rule 81", Weight: 1},
	{Code: "ROUTE_082", Description: "validated route workflow rule 82", Weight: 2},
	{Code: "ROUTE_083", Description: "validated route workflow rule 83", Weight: 3},
	{Code: "ROUTE_084", Description: "validated route workflow rule 84", Weight: 4},
	{Code: "ROUTE_085", Description: "validated route workflow rule 85", Weight: 5},
	{Code: "ROUTE_086", Description: "validated route workflow rule 86", Weight: 6},
	{Code: "ROUTE_087", Description: "validated route workflow rule 87", Weight: 7},
	{Code: "ROUTE_088", Description: "validated route workflow rule 88", Weight: 8},
	{Code: "ROUTE_089", Description: "validated route workflow rule 89", Weight: 9},
	{Code: "ROUTE_090", Description: "validated route workflow rule 90", Weight: 1},
	{Code: "ROUTE_091", Description: "validated route workflow rule 91", Weight: 2},
	{Code: "ROUTE_092", Description: "validated route workflow rule 92", Weight: 3},
	{Code: "ROUTE_093", Description: "validated route workflow rule 93", Weight: 4},
	{Code: "ROUTE_094", Description: "validated route workflow rule 94", Weight: 5},
	{Code: "ROUTE_095", Description: "validated route workflow rule 95", Weight: 6},
	{Code: "ROUTE_096", Description: "validated route workflow rule 96", Weight: 7},
	{Code: "ROUTE_097", Description: "validated route workflow rule 97", Weight: 8},
	{Code: "ROUTE_098", Description: "validated route workflow rule 98", Weight: 9},
	{Code: "ROUTE_099", Description: "validated route workflow rule 99", Weight: 1},
	{Code: "ROUTE_100", Description: "validated route workflow rule 100", Weight: 2},
	{Code: "ROUTE_101", Description: "validated route workflow rule 101", Weight: 3},
	{Code: "ROUTE_102", Description: "validated route workflow rule 102", Weight: 4},
	{Code: "ROUTE_103", Description: "validated route workflow rule 103", Weight: 5},
	{Code: "ROUTE_104", Description: "validated route workflow rule 104", Weight: 6},
	{Code: "ROUTE_105", Description: "validated route workflow rule 105", Weight: 7},
	{Code: "ROUTE_106", Description: "validated route workflow rule 106", Weight: 8},
	{Code: "ROUTE_107", Description: "validated route workflow rule 107", Weight: 9},
	{Code: "ROUTE_108", Description: "validated route workflow rule 108", Weight: 1},
	{Code: "ROUTE_109", Description: "validated route workflow rule 109", Weight: 2},
	{Code: "ROUTE_110", Description: "validated route workflow rule 110", Weight: 3},
	{Code: "ROUTE_111", Description: "validated route workflow rule 111", Weight: 4},
	{Code: "ROUTE_112", Description: "validated route workflow rule 112", Weight: 5},
	{Code: "ROUTE_113", Description: "validated route workflow rule 113", Weight: 6},
	{Code: "ROUTE_114", Description: "validated route workflow rule 114", Weight: 7},
	{Code: "ROUTE_115", Description: "validated route workflow rule 115", Weight: 8},
	{Code: "ROUTE_116", Description: "validated route workflow rule 116", Weight: 9},
	{Code: "ROUTE_117", Description: "validated route workflow rule 117", Weight: 1},
	{Code: "ROUTE_118", Description: "validated route workflow rule 118", Weight: 2},
	{Code: "ROUTE_119", Description: "validated route workflow rule 119", Weight: 3},
	{Code: "ROUTE_120", Description: "validated route workflow rule 120", Weight: 4},
	{Code: "ROUTE_121", Description: "validated route workflow rule 121", Weight: 5},
	{Code: "ROUTE_122", Description: "validated route workflow rule 122", Weight: 6},
	{Code: "ROUTE_123", Description: "validated route workflow rule 123", Weight: 7},
	{Code: "ROUTE_124", Description: "validated route workflow rule 124", Weight: 8},
	{Code: "ROUTE_125", Description: "validated route workflow rule 125", Weight: 9},
	{Code: "ROUTE_126", Description: "validated route workflow rule 126", Weight: 1},
	{Code: "ROUTE_127", Description: "validated route workflow rule 127", Weight: 2},
	{Code: "ROUTE_128", Description: "validated route workflow rule 128", Weight: 3},
	{Code: "ROUTE_129", Description: "validated route workflow rule 129", Weight: 4},
	{Code: "ROUTE_130", Description: "validated route workflow rule 130", Weight: 5},
	{Code: "ROUTE_131", Description: "validated route workflow rule 131", Weight: 6},
	{Code: "ROUTE_132", Description: "validated route workflow rule 132", Weight: 7},
	{Code: "ROUTE_133", Description: "validated route workflow rule 133", Weight: 8},
	{Code: "ROUTE_134", Description: "validated route workflow rule 134", Weight: 9},
	{Code: "ROUTE_135", Description: "validated route workflow rule 135", Weight: 1},
	{Code: "ROUTE_136", Description: "validated route workflow rule 136", Weight: 2},
	{Code: "ROUTE_137", Description: "validated route workflow rule 137", Weight: 3},
	{Code: "ROUTE_138", Description: "validated route workflow rule 138", Weight: 4},
	{Code: "ROUTE_139", Description: "validated route workflow rule 139", Weight: 5},
	{Code: "ROUTE_140", Description: "validated route workflow rule 140", Weight: 6},
	{Code: "ROUTE_141", Description: "validated route workflow rule 141", Weight: 7},
	{Code: "ROUTE_142", Description: "validated route workflow rule 142", Weight: 8},
	{Code: "ROUTE_143", Description: "validated route workflow rule 143", Weight: 9},
	{Code: "ROUTE_144", Description: "validated route workflow rule 144", Weight: 1},
	{Code: "ROUTE_145", Description: "validated route workflow rule 145", Weight: 2},
	{Code: "ROUTE_146", Description: "validated route workflow rule 146", Weight: 3},
	{Code: "ROUTE_147", Description: "validated route workflow rule 147", Weight: 4},
	{Code: "ROUTE_148", Description: "validated route workflow rule 148", Weight: 5},
	{Code: "ROUTE_149", Description: "validated route workflow rule 149", Weight: 6},
	{Code: "ROUTE_150", Description: "validated route workflow rule 150", Weight: 7},
	{Code: "ROUTE_151", Description: "validated route workflow rule 151", Weight: 8},
	{Code: "ROUTE_152", Description: "validated route workflow rule 152", Weight: 9},
	{Code: "ROUTE_153", Description: "validated route workflow rule 153", Weight: 1},
	{Code: "ROUTE_154", Description: "validated route workflow rule 154", Weight: 2},
	{Code: "ROUTE_155", Description: "validated route workflow rule 155", Weight: 3},
	{Code: "ROUTE_156", Description: "validated route workflow rule 156", Weight: 4},
	{Code: "ROUTE_157", Description: "validated route workflow rule 157", Weight: 5},
	{Code: "ROUTE_158", Description: "validated route workflow rule 158", Weight: 6},
	{Code: "ROUTE_159", Description: "validated route workflow rule 159", Weight: 7},
	{Code: "ROUTE_160", Description: "validated route workflow rule 160", Weight: 8},
	{Code: "ROUTE_161", Description: "validated route workflow rule 161", Weight: 9},
	{Code: "ROUTE_162", Description: "validated route workflow rule 162", Weight: 1},
	{Code: "ROUTE_163", Description: "validated route workflow rule 163", Weight: 2},
	{Code: "ROUTE_164", Description: "validated route workflow rule 164", Weight: 3},
	{Code: "ROUTE_165", Description: "validated route workflow rule 165", Weight: 4},
	{Code: "ROUTE_166", Description: "validated route workflow rule 166", Weight: 5},
	{Code: "ROUTE_167", Description: "validated route workflow rule 167", Weight: 6},
	{Code: "ROUTE_168", Description: "validated route workflow rule 168", Weight: 7},
	{Code: "ROUTE_169", Description: "validated route workflow rule 169", Weight: 8},
	{Code: "ROUTE_170", Description: "validated route workflow rule 170", Weight: 9},
	{Code: "ROUTE_171", Description: "validated route workflow rule 171", Weight: 1},
	{Code: "ROUTE_172", Description: "validated route workflow rule 172", Weight: 2},
	{Code: "ROUTE_173", Description: "validated route workflow rule 173", Weight: 3},
	{Code: "ROUTE_174", Description: "validated route workflow rule 174", Weight: 4},
	{Code: "ROUTE_175", Description: "validated route workflow rule 175", Weight: 5},
	{Code: "ROUTE_176", Description: "validated route workflow rule 176", Weight: 6},
	{Code: "ROUTE_177", Description: "validated route workflow rule 177", Weight: 7},
	{Code: "ROUTE_178", Description: "validated route workflow rule 178", Weight: 8},
	{Code: "ROUTE_179", Description: "validated route workflow rule 179", Weight: 9},
	{Code: "ROUTE_180", Description: "validated route workflow rule 180", Weight: 1},
	{Code: "ROUTE_181", Description: "validated route workflow rule 181", Weight: 2},
	{Code: "ROUTE_182", Description: "validated route workflow rule 182", Weight: 3},
	{Code: "ROUTE_183", Description: "validated route workflow rule 183", Weight: 4},
	{Code: "ROUTE_184", Description: "validated route workflow rule 184", Weight: 5},
	{Code: "ROUTE_185", Description: "validated route workflow rule 185", Weight: 6},
	{Code: "ROUTE_186", Description: "validated route workflow rule 186", Weight: 7},
	{Code: "ROUTE_187", Description: "validated route workflow rule 187", Weight: 8},
	{Code: "ROUTE_188", Description: "validated route workflow rule 188", Weight: 9},
	{Code: "ROUTE_189", Description: "validated route workflow rule 189", Weight: 1},
	{Code: "ROUTE_190", Description: "validated route workflow rule 190", Weight: 2},
	{Code: "ROUTE_191", Description: "validated route workflow rule 191", Weight: 3},
	{Code: "ROUTE_192", Description: "validated route workflow rule 192", Weight: 4},
	{Code: "ROUTE_193", Description: "validated route workflow rule 193", Weight: 5},
	{Code: "ROUTE_194", Description: "validated route workflow rule 194", Weight: 6},
	{Code: "ROUTE_195", Description: "validated route workflow rule 195", Weight: 7},
	{Code: "ROUTE_196", Description: "validated route workflow rule 196", Weight: 8},
	{Code: "ROUTE_197", Description: "validated route workflow rule 197", Weight: 9},
	{Code: "ROUTE_198", Description: "validated route workflow rule 198", Weight: 1},
	{Code: "ROUTE_199", Description: "validated route workflow rule 199", Weight: 2},
	{Code: "ROUTE_200", Description: "validated route workflow rule 200", Weight: 3},
	{Code: "ROUTE_201", Description: "validated route workflow rule 201", Weight: 4},
	{Code: "ROUTE_202", Description: "validated route workflow rule 202", Weight: 5},
	{Code: "ROUTE_203", Description: "validated route workflow rule 203", Weight: 6},
	{Code: "ROUTE_204", Description: "validated route workflow rule 204", Weight: 7},
	{Code: "ROUTE_205", Description: "validated route workflow rule 205", Weight: 8},
	{Code: "ROUTE_206", Description: "validated route workflow rule 206", Weight: 9},
	{Code: "ROUTE_207", Description: "validated route workflow rule 207", Weight: 1},
	{Code: "ROUTE_208", Description: "validated route workflow rule 208", Weight: 2},
	{Code: "ROUTE_209", Description: "validated route workflow rule 209", Weight: 3},
	{Code: "ROUTE_210", Description: "validated route workflow rule 210", Weight: 4},
	{Code: "ROUTE_211", Description: "validated route workflow rule 211", Weight: 5},
	{Code: "ROUTE_212", Description: "validated route workflow rule 212", Weight: 6},
	{Code: "ROUTE_213", Description: "validated route workflow rule 213", Weight: 7},
	{Code: "ROUTE_214", Description: "validated route workflow rule 214", Weight: 8},
	{Code: "ROUTE_215", Description: "validated route workflow rule 215", Weight: 9},
	{Code: "ROUTE_216", Description: "validated route workflow rule 216", Weight: 1},
	{Code: "ROUTE_217", Description: "validated route workflow rule 217", Weight: 2},
	{Code: "ROUTE_218", Description: "validated route workflow rule 218", Weight: 3},
	{Code: "ROUTE_219", Description: "validated route workflow rule 219", Weight: 4},
	{Code: "ROUTE_220", Description: "validated route workflow rule 220", Weight: 5},
}

func RouteRuleByCode(code string) (RouteRule, bool) {
	for _, r := range RouteRules {
		if r.Code == code {
			return r, true
		}
	}
	return RouteRule{}, false
}

func RouteRuleScore(code string) int {
	r, ok := RouteRuleByCode(code)
	if !ok {
		return 0
	}
	return r.Weight
}

func RouteRuleCount() int { return len(RouteRules) }
