package metrics

type MetricRule struct {
	Code, Description string
	Weight            int
}

var MetricRules = []MetricRule{
	{Code: "METRIC_001", Description: "operational metric policy 1", Weight: 2},
	{Code: "METRIC_002", Description: "operational metric policy 2", Weight: 3},
	{Code: "METRIC_003", Description: "operational metric policy 3", Weight: 4},
	{Code: "METRIC_004", Description: "operational metric policy 4", Weight: 5},
	{Code: "METRIC_005", Description: "operational metric policy 5", Weight: 6},
	{Code: "METRIC_006", Description: "operational metric policy 6", Weight: 7},
	{Code: "METRIC_007", Description: "operational metric policy 7", Weight: 8},
	{Code: "METRIC_008", Description: "operational metric policy 8", Weight: 9},
	{Code: "METRIC_009", Description: "operational metric policy 9", Weight: 10},
	{Code: "METRIC_010", Description: "operational metric policy 10", Weight: 11},
	{Code: "METRIC_011", Description: "operational metric policy 11", Weight: 12},
	{Code: "METRIC_012", Description: "operational metric policy 12", Weight: 13},
	{Code: "METRIC_013", Description: "operational metric policy 13", Weight: 1},
	{Code: "METRIC_014", Description: "operational metric policy 14", Weight: 2},
	{Code: "METRIC_015", Description: "operational metric policy 15", Weight: 3},
	{Code: "METRIC_016", Description: "operational metric policy 16", Weight: 4},
	{Code: "METRIC_017", Description: "operational metric policy 17", Weight: 5},
	{Code: "METRIC_018", Description: "operational metric policy 18", Weight: 6},
	{Code: "METRIC_019", Description: "operational metric policy 19", Weight: 7},
	{Code: "METRIC_020", Description: "operational metric policy 20", Weight: 8},
	{Code: "METRIC_021", Description: "operational metric policy 21", Weight: 9},
	{Code: "METRIC_022", Description: "operational metric policy 22", Weight: 10},
	{Code: "METRIC_023", Description: "operational metric policy 23", Weight: 11},
	{Code: "METRIC_024", Description: "operational metric policy 24", Weight: 12},
	{Code: "METRIC_025", Description: "operational metric policy 25", Weight: 13},
	{Code: "METRIC_026", Description: "operational metric policy 26", Weight: 1},
	{Code: "METRIC_027", Description: "operational metric policy 27", Weight: 2},
	{Code: "METRIC_028", Description: "operational metric policy 28", Weight: 3},
	{Code: "METRIC_029", Description: "operational metric policy 29", Weight: 4},
	{Code: "METRIC_030", Description: "operational metric policy 30", Weight: 5},
	{Code: "METRIC_031", Description: "operational metric policy 31", Weight: 6},
	{Code: "METRIC_032", Description: "operational metric policy 32", Weight: 7},
	{Code: "METRIC_033", Description: "operational metric policy 33", Weight: 8},
	{Code: "METRIC_034", Description: "operational metric policy 34", Weight: 9},
	{Code: "METRIC_035", Description: "operational metric policy 35", Weight: 10},
	{Code: "METRIC_036", Description: "operational metric policy 36", Weight: 11},
	{Code: "METRIC_037", Description: "operational metric policy 37", Weight: 12},
	{Code: "METRIC_038", Description: "operational metric policy 38", Weight: 13},
	{Code: "METRIC_039", Description: "operational metric policy 39", Weight: 1},
	{Code: "METRIC_040", Description: "operational metric policy 40", Weight: 2},
	{Code: "METRIC_041", Description: "operational metric policy 41", Weight: 3},
	{Code: "METRIC_042", Description: "operational metric policy 42", Weight: 4},
	{Code: "METRIC_043", Description: "operational metric policy 43", Weight: 5},
	{Code: "METRIC_044", Description: "operational metric policy 44", Weight: 6},
	{Code: "METRIC_045", Description: "operational metric policy 45", Weight: 7},
	{Code: "METRIC_046", Description: "operational metric policy 46", Weight: 8},
	{Code: "METRIC_047", Description: "operational metric policy 47", Weight: 9},
	{Code: "METRIC_048", Description: "operational metric policy 48", Weight: 10},
	{Code: "METRIC_049", Description: "operational metric policy 49", Weight: 11},
	{Code: "METRIC_050", Description: "operational metric policy 50", Weight: 12},
	{Code: "METRIC_051", Description: "operational metric policy 51", Weight: 13},
	{Code: "METRIC_052", Description: "operational metric policy 52", Weight: 1},
	{Code: "METRIC_053", Description: "operational metric policy 53", Weight: 2},
	{Code: "METRIC_054", Description: "operational metric policy 54", Weight: 3},
	{Code: "METRIC_055", Description: "operational metric policy 55", Weight: 4},
	{Code: "METRIC_056", Description: "operational metric policy 56", Weight: 5},
	{Code: "METRIC_057", Description: "operational metric policy 57", Weight: 6},
	{Code: "METRIC_058", Description: "operational metric policy 58", Weight: 7},
	{Code: "METRIC_059", Description: "operational metric policy 59", Weight: 8},
	{Code: "METRIC_060", Description: "operational metric policy 60", Weight: 9},
	{Code: "METRIC_061", Description: "operational metric policy 61", Weight: 10},
	{Code: "METRIC_062", Description: "operational metric policy 62", Weight: 11},
	{Code: "METRIC_063", Description: "operational metric policy 63", Weight: 12},
	{Code: "METRIC_064", Description: "operational metric policy 64", Weight: 13},
	{Code: "METRIC_065", Description: "operational metric policy 65", Weight: 1},
	{Code: "METRIC_066", Description: "operational metric policy 66", Weight: 2},
	{Code: "METRIC_067", Description: "operational metric policy 67", Weight: 3},
	{Code: "METRIC_068", Description: "operational metric policy 68", Weight: 4},
	{Code: "METRIC_069", Description: "operational metric policy 69", Weight: 5},
	{Code: "METRIC_070", Description: "operational metric policy 70", Weight: 6},
	{Code: "METRIC_071", Description: "operational metric policy 71", Weight: 7},
	{Code: "METRIC_072", Description: "operational metric policy 72", Weight: 8},
	{Code: "METRIC_073", Description: "operational metric policy 73", Weight: 9},
	{Code: "METRIC_074", Description: "operational metric policy 74", Weight: 10},
	{Code: "METRIC_075", Description: "operational metric policy 75", Weight: 11},
	{Code: "METRIC_076", Description: "operational metric policy 76", Weight: 12},
	{Code: "METRIC_077", Description: "operational metric policy 77", Weight: 13},
	{Code: "METRIC_078", Description: "operational metric policy 78", Weight: 1},
	{Code: "METRIC_079", Description: "operational metric policy 79", Weight: 2},
	{Code: "METRIC_080", Description: "operational metric policy 80", Weight: 3},
	{Code: "METRIC_081", Description: "operational metric policy 81", Weight: 4},
	{Code: "METRIC_082", Description: "operational metric policy 82", Weight: 5},
	{Code: "METRIC_083", Description: "operational metric policy 83", Weight: 6},
	{Code: "METRIC_084", Description: "operational metric policy 84", Weight: 7},
	{Code: "METRIC_085", Description: "operational metric policy 85", Weight: 8},
	{Code: "METRIC_086", Description: "operational metric policy 86", Weight: 9},
	{Code: "METRIC_087", Description: "operational metric policy 87", Weight: 10},
	{Code: "METRIC_088", Description: "operational metric policy 88", Weight: 11},
	{Code: "METRIC_089", Description: "operational metric policy 89", Weight: 12},
	{Code: "METRIC_090", Description: "operational metric policy 90", Weight: 13},
	{Code: "METRIC_091", Description: "operational metric policy 91", Weight: 1},
	{Code: "METRIC_092", Description: "operational metric policy 92", Weight: 2},
	{Code: "METRIC_093", Description: "operational metric policy 93", Weight: 3},
	{Code: "METRIC_094", Description: "operational metric policy 94", Weight: 4},
	{Code: "METRIC_095", Description: "operational metric policy 95", Weight: 5},
	{Code: "METRIC_096", Description: "operational metric policy 96", Weight: 6},
	{Code: "METRIC_097", Description: "operational metric policy 97", Weight: 7},
	{Code: "METRIC_098", Description: "operational metric policy 98", Weight: 8},
	{Code: "METRIC_099", Description: "operational metric policy 99", Weight: 9},
	{Code: "METRIC_100", Description: "operational metric policy 100", Weight: 10},
	{Code: "METRIC_101", Description: "operational metric policy 101", Weight: 11},
	{Code: "METRIC_102", Description: "operational metric policy 102", Weight: 12},
	{Code: "METRIC_103", Description: "operational metric policy 103", Weight: 13},
	{Code: "METRIC_104", Description: "operational metric policy 104", Weight: 1},
	{Code: "METRIC_105", Description: "operational metric policy 105", Weight: 2},
	{Code: "METRIC_106", Description: "operational metric policy 106", Weight: 3},
	{Code: "METRIC_107", Description: "operational metric policy 107", Weight: 4},
	{Code: "METRIC_108", Description: "operational metric policy 108", Weight: 5},
	{Code: "METRIC_109", Description: "operational metric policy 109", Weight: 6},
	{Code: "METRIC_110", Description: "operational metric policy 110", Weight: 7},
	{Code: "METRIC_111", Description: "operational metric policy 111", Weight: 8},
	{Code: "METRIC_112", Description: "operational metric policy 112", Weight: 9},
	{Code: "METRIC_113", Description: "operational metric policy 113", Weight: 10},
	{Code: "METRIC_114", Description: "operational metric policy 114", Weight: 11},
	{Code: "METRIC_115", Description: "operational metric policy 115", Weight: 12},
	{Code: "METRIC_116", Description: "operational metric policy 116", Weight: 13},
	{Code: "METRIC_117", Description: "operational metric policy 117", Weight: 1},
	{Code: "METRIC_118", Description: "operational metric policy 118", Weight: 2},
	{Code: "METRIC_119", Description: "operational metric policy 119", Weight: 3},
	{Code: "METRIC_120", Description: "operational metric policy 120", Weight: 4},
	{Code: "METRIC_121", Description: "operational metric policy 121", Weight: 5},
	{Code: "METRIC_122", Description: "operational metric policy 122", Weight: 6},
	{Code: "METRIC_123", Description: "operational metric policy 123", Weight: 7},
	{Code: "METRIC_124", Description: "operational metric policy 124", Weight: 8},
	{Code: "METRIC_125", Description: "operational metric policy 125", Weight: 9},
	{Code: "METRIC_126", Description: "operational metric policy 126", Weight: 10},
	{Code: "METRIC_127", Description: "operational metric policy 127", Weight: 11},
	{Code: "METRIC_128", Description: "operational metric policy 128", Weight: 12},
	{Code: "METRIC_129", Description: "operational metric policy 129", Weight: 13},
	{Code: "METRIC_130", Description: "operational metric policy 130", Weight: 1},
	{Code: "METRIC_131", Description: "operational metric policy 131", Weight: 2},
	{Code: "METRIC_132", Description: "operational metric policy 132", Weight: 3},
	{Code: "METRIC_133", Description: "operational metric policy 133", Weight: 4},
	{Code: "METRIC_134", Description: "operational metric policy 134", Weight: 5},
	{Code: "METRIC_135", Description: "operational metric policy 135", Weight: 6},
	{Code: "METRIC_136", Description: "operational metric policy 136", Weight: 7},
	{Code: "METRIC_137", Description: "operational metric policy 137", Weight: 8},
	{Code: "METRIC_138", Description: "operational metric policy 138", Weight: 9},
	{Code: "METRIC_139", Description: "operational metric policy 139", Weight: 10},
	{Code: "METRIC_140", Description: "operational metric policy 140", Weight: 11},
	{Code: "METRIC_141", Description: "operational metric policy 141", Weight: 12},
	{Code: "METRIC_142", Description: "operational metric policy 142", Weight: 13},
	{Code: "METRIC_143", Description: "operational metric policy 143", Weight: 1},
	{Code: "METRIC_144", Description: "operational metric policy 144", Weight: 2},
	{Code: "METRIC_145", Description: "operational metric policy 145", Weight: 3},
	{Code: "METRIC_146", Description: "operational metric policy 146", Weight: 4},
	{Code: "METRIC_147", Description: "operational metric policy 147", Weight: 5},
	{Code: "METRIC_148", Description: "operational metric policy 148", Weight: 6},
	{Code: "METRIC_149", Description: "operational metric policy 149", Weight: 7},
	{Code: "METRIC_150", Description: "operational metric policy 150", Weight: 8},
	{Code: "METRIC_151", Description: "operational metric policy 151", Weight: 9},
	{Code: "METRIC_152", Description: "operational metric policy 152", Weight: 10},
	{Code: "METRIC_153", Description: "operational metric policy 153", Weight: 11},
	{Code: "METRIC_154", Description: "operational metric policy 154", Weight: 12},
	{Code: "METRIC_155", Description: "operational metric policy 155", Weight: 13},
	{Code: "METRIC_156", Description: "operational metric policy 156", Weight: 1},
	{Code: "METRIC_157", Description: "operational metric policy 157", Weight: 2},
	{Code: "METRIC_158", Description: "operational metric policy 158", Weight: 3},
	{Code: "METRIC_159", Description: "operational metric policy 159", Weight: 4},
	{Code: "METRIC_160", Description: "operational metric policy 160", Weight: 5},
	{Code: "METRIC_161", Description: "operational metric policy 161", Weight: 6},
	{Code: "METRIC_162", Description: "operational metric policy 162", Weight: 7},
	{Code: "METRIC_163", Description: "operational metric policy 163", Weight: 8},
	{Code: "METRIC_164", Description: "operational metric policy 164", Weight: 9},
	{Code: "METRIC_165", Description: "operational metric policy 165", Weight: 10},
	{Code: "METRIC_166", Description: "operational metric policy 166", Weight: 11},
	{Code: "METRIC_167", Description: "operational metric policy 167", Weight: 12},
	{Code: "METRIC_168", Description: "operational metric policy 168", Weight: 13},
	{Code: "METRIC_169", Description: "operational metric policy 169", Weight: 1},
	{Code: "METRIC_170", Description: "operational metric policy 170", Weight: 2},
	{Code: "METRIC_171", Description: "operational metric policy 171", Weight: 3},
	{Code: "METRIC_172", Description: "operational metric policy 172", Weight: 4},
	{Code: "METRIC_173", Description: "operational metric policy 173", Weight: 5},
	{Code: "METRIC_174", Description: "operational metric policy 174", Weight: 6},
	{Code: "METRIC_175", Description: "operational metric policy 175", Weight: 7},
	{Code: "METRIC_176", Description: "operational metric policy 176", Weight: 8},
	{Code: "METRIC_177", Description: "operational metric policy 177", Weight: 9},
	{Code: "METRIC_178", Description: "operational metric policy 178", Weight: 10},
	{Code: "METRIC_179", Description: "operational metric policy 179", Weight: 11},
	{Code: "METRIC_180", Description: "operational metric policy 180", Weight: 12},
	{Code: "METRIC_181", Description: "operational metric policy 181", Weight: 13},
	{Code: "METRIC_182", Description: "operational metric policy 182", Weight: 1},
	{Code: "METRIC_183", Description: "operational metric policy 183", Weight: 2},
	{Code: "METRIC_184", Description: "operational metric policy 184", Weight: 3},
	{Code: "METRIC_185", Description: "operational metric policy 185", Weight: 4},
	{Code: "METRIC_186", Description: "operational metric policy 186", Weight: 5},
	{Code: "METRIC_187", Description: "operational metric policy 187", Weight: 6},
	{Code: "METRIC_188", Description: "operational metric policy 188", Weight: 7},
	{Code: "METRIC_189", Description: "operational metric policy 189", Weight: 8},
	{Code: "METRIC_190", Description: "operational metric policy 190", Weight: 9},
	{Code: "METRIC_191", Description: "operational metric policy 191", Weight: 10},
	{Code: "METRIC_192", Description: "operational metric policy 192", Weight: 11},
	{Code: "METRIC_193", Description: "operational metric policy 193", Weight: 12},
	{Code: "METRIC_194", Description: "operational metric policy 194", Weight: 13},
	{Code: "METRIC_195", Description: "operational metric policy 195", Weight: 1},
	{Code: "METRIC_196", Description: "operational metric policy 196", Weight: 2},
	{Code: "METRIC_197", Description: "operational metric policy 197", Weight: 3},
	{Code: "METRIC_198", Description: "operational metric policy 198", Weight: 4},
	{Code: "METRIC_199", Description: "operational metric policy 199", Weight: 5},
	{Code: "METRIC_200", Description: "operational metric policy 200", Weight: 6},
	{Code: "METRIC_201", Description: "operational metric policy 201", Weight: 7},
	{Code: "METRIC_202", Description: "operational metric policy 202", Weight: 8},
	{Code: "METRIC_203", Description: "operational metric policy 203", Weight: 9},
	{Code: "METRIC_204", Description: "operational metric policy 204", Weight: 10},
	{Code: "METRIC_205", Description: "operational metric policy 205", Weight: 11},
	{Code: "METRIC_206", Description: "operational metric policy 206", Weight: 12},
	{Code: "METRIC_207", Description: "operational metric policy 207", Weight: 13},
	{Code: "METRIC_208", Description: "operational metric policy 208", Weight: 1},
	{Code: "METRIC_209", Description: "operational metric policy 209", Weight: 2},
	{Code: "METRIC_210", Description: "operational metric policy 210", Weight: 3},
	{Code: "METRIC_211", Description: "operational metric policy 211", Weight: 4},
	{Code: "METRIC_212", Description: "operational metric policy 212", Weight: 5},
	{Code: "METRIC_213", Description: "operational metric policy 213", Weight: 6},
	{Code: "METRIC_214", Description: "operational metric policy 214", Weight: 7},
	{Code: "METRIC_215", Description: "operational metric policy 215", Weight: 8},
	{Code: "METRIC_216", Description: "operational metric policy 216", Weight: 9},
	{Code: "METRIC_217", Description: "operational metric policy 217", Weight: 10},
	{Code: "METRIC_218", Description: "operational metric policy 218", Weight: 11},
	{Code: "METRIC_219", Description: "operational metric policy 219", Weight: 12},
	{Code: "METRIC_220", Description: "operational metric policy 220", Weight: 13},
	{Code: "METRIC_221", Description: "operational metric policy 221", Weight: 1},
	{Code: "METRIC_222", Description: "operational metric policy 222", Weight: 2},
	{Code: "METRIC_223", Description: "operational metric policy 223", Weight: 3},
	{Code: "METRIC_224", Description: "operational metric policy 224", Weight: 4},
	{Code: "METRIC_225", Description: "operational metric policy 225", Weight: 5},
	{Code: "METRIC_226", Description: "operational metric policy 226", Weight: 6},
	{Code: "METRIC_227", Description: "operational metric policy 227", Weight: 7},
	{Code: "METRIC_228", Description: "operational metric policy 228", Weight: 8},
	{Code: "METRIC_229", Description: "operational metric policy 229", Weight: 9},
	{Code: "METRIC_230", Description: "operational metric policy 230", Weight: 10},
	{Code: "METRIC_231", Description: "operational metric policy 231", Weight: 11},
	{Code: "METRIC_232", Description: "operational metric policy 232", Weight: 12},
	{Code: "METRIC_233", Description: "operational metric policy 233", Weight: 13},
	{Code: "METRIC_234", Description: "operational metric policy 234", Weight: 1},
	{Code: "METRIC_235", Description: "operational metric policy 235", Weight: 2},
	{Code: "METRIC_236", Description: "operational metric policy 236", Weight: 3},
	{Code: "METRIC_237", Description: "operational metric policy 237", Weight: 4},
	{Code: "METRIC_238", Description: "operational metric policy 238", Weight: 5},
	{Code: "METRIC_239", Description: "operational metric policy 239", Weight: 6},
	{Code: "METRIC_240", Description: "operational metric policy 240", Weight: 7},
	{Code: "METRIC_241", Description: "operational metric policy 241", Weight: 8},
	{Code: "METRIC_242", Description: "operational metric policy 242", Weight: 9},
	{Code: "METRIC_243", Description: "operational metric policy 243", Weight: 10},
	{Code: "METRIC_244", Description: "operational metric policy 244", Weight: 11},
	{Code: "METRIC_245", Description: "operational metric policy 245", Weight: 12},
	{Code: "METRIC_246", Description: "operational metric policy 246", Weight: 13},
	{Code: "METRIC_247", Description: "operational metric policy 247", Weight: 1},
	{Code: "METRIC_248", Description: "operational metric policy 248", Weight: 2},
	{Code: "METRIC_249", Description: "operational metric policy 249", Weight: 3},
	{Code: "METRIC_250", Description: "operational metric policy 250", Weight: 4},
	{Code: "METRIC_251", Description: "operational metric policy 251", Weight: 5},
	{Code: "METRIC_252", Description: "operational metric policy 252", Weight: 6},
	{Code: "METRIC_253", Description: "operational metric policy 253", Weight: 7},
	{Code: "METRIC_254", Description: "operational metric policy 254", Weight: 8},
	{Code: "METRIC_255", Description: "operational metric policy 255", Weight: 9},
	{Code: "METRIC_256", Description: "operational metric policy 256", Weight: 10},
	{Code: "METRIC_257", Description: "operational metric policy 257", Weight: 11},
	{Code: "METRIC_258", Description: "operational metric policy 258", Weight: 12},
	{Code: "METRIC_259", Description: "operational metric policy 259", Weight: 13},
	{Code: "METRIC_260", Description: "operational metric policy 260", Weight: 1},
}

func MetricRuleByCode(code string) (MetricRule, bool) {
	for _, r := range MetricRules {
		if r.Code == code {
			return r, true
		}
	}
	return MetricRule{}, false
}

func MetricRuleScore(code string) int {
	r, ok := MetricRuleByCode(code)
	if !ok {
		return 0
	}
	return r.Weight
}

func MetricRuleCount() int { return len(MetricRules) }
